### ISSUE TITLE
Color Hex Color Codes

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#141]
_From @blackearth2014 on February 18, 2016 3:3_

Is it possible to have the ability to enter Color Hex Color Codes as colors. It will help entering colors that you like faster.

![color hex color codes](https://cloud.githubusercontent.com/assets/7956901/13132591/197a5d44-d5c2-11e5-8a1d-bf1a8744b81a.png)

_Copied from original issue: MrKepzie/Natron#1188_

**Comment by devernay** [comment]
_From @sobotka on February 22, 2016 4:32_

Hex values don't mean anything as RGB is a relative colour encoding model.

That means the image above likely is assuming something it isn't telling you: the assumed space is based on REC.709 primaries.

**Comment by devernay** [comment]
This could be added to the future color picker.
@blackearth2014 blackearth2014, I suppose you expect those colors to be sRGB ("web" colors) ?

**Comment by devernay** [comment]
_From @blackearth2014 on March 4, 2016 18:38_

Thanks @devernay. Yes sRGB (Web Colors).

**Comment by devernay** [comment]
_From @mray on November 9, 2016 0:28_

This would be much appreciated since it allows easy copy from other tools (like Inkscape).
It is only copy+paste _once_.

**Comment by Shrinks99** [comment]
This has since been added to Natron's colour picker but how the heck does it even work?  Hex codes only represent a tiny fraction of representable colours.  Does Natron just linearlize, assume the working space is 709 and set the RGB values accordingly?

**Comment by devernay** [comment]
I don't think hex codes are supported.

As for the color dialog (not picker), it is the 8-bit color picker from Qt, and yes values are assumed to be using the sRGB transfer function and are simply linearized individually.

The color picker picks the RGB values from the viewer, so you have floating-point precision. You could for example generate a color palette EXR image, and use that with the color picker.

**Comment by Shrinks99** [comment]
Am a dummy, I thought it was a part of that dialogue, didn't check before posting.

As for the Qt color picker, I figured as much.  Good to know.

**Comment by rodlie** [comment]
I can add hex to the dialog if wanted.

**Comment by Shrinks99** [comment]
If anything it probably _shouldn't_ be added and the 8-bit colour dialogue considered in need of eventual replacement.  Hex codes don't work properly in anything other than sRGB and while I'm sure some find them useful when working in this space they are broken and will not function accurately in any other gamut.

**Comment by rodlie** [comment]
> and the 8-bit colour dialogue considered in need of eventual replacement

As you know I'm working on the color knob stuff, don't know when I'm done.

> I'm sure some find them useful when working in this space they are broken

Probably, but if a user want's to use hex they should be allowed to do so.

**Comment by rodlie** [comment]
close as this feature has been added in https://github.com/NatronGitHub/Natron/issues/201 (not merged yet).

**Comment by sobotka** [comment]
Hex codes are an absolutely horrific idea that serve no other purpose other than to obfuscate the fact that the meaning of the number is a percentage of emission from a display.

Horrible, horrible idea.

**Comment by rodlie** [comment]
I understand where you are coming from, but Natron is a tool for artists, and creative tools should not lecture users on what they can or can't do. If a user want's to paste a hex code the tool should allow that IMHO.

I will leave the final decision to someone else (as I have nothing more to add to this discussion).

**Comment by Shrinks99** [comment]
Troy's problem with hex codes is both a semantic and technical one.  I've discussed this issue with him at length and he has many good points to make, I'll try to lay all of them out here and I'll give my opinion too which is more nuanced than "hex codes are bad" and notability one that Troy doesn't entirely agree with.

### The deal with hex codes

Hex codes obfuscate the data that they consist of.  They decode to three, 8-bit integers that range from 0-255, 0 representing black (0% pixel emission), and 255 representing 100% pixel emission in the sRGB space and _only_ in that space.  Hex codes are objectively broken in any other space and do not give accurate results.<sup>1</sup>

If you asked most people how a hex code worked they would not be able to recite the above explanation, you might get an answer like "it's the code for that colour" or "it lets you transfer colours between programs".  They are not a human friendly format and as such they contribute to a bad understanding of what digital colour actually _is_, a problem that I'm passionate about as well.  By adding them to the program, Natron is arguably contributing to that problem by advocating and allowing their use.

So why _are_ hex codes used then?  Well in many pieces of high-end professional creative software they aren't!  [Maya](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2015/ENU/Maya/files/Basics-Windows-and-Editors-Color-Chooser-htm.html), [Nuke](https://learn.foundry.com/nuke/content/getting_started/using_interface/using_color_controls.html), and [Houdini](https://www.sidefx.com/docs/houdini/ref/windows/coloreditor.html) have all chosen not to implement them, likely because their developers _and users_ are aware of the problems presented by the format.  For the rest of the world that doesn't know as much about digital colour, they represent a single string that one can copy from one application to another.  The same colour will appear on the screen because the computer understands the magic 6 character code.  They have become another dumb defacto standard (probably popularized by Adobe and the W3C) because there _isn't_ a better standardized way to paste RGB triplets themselves between programs, and most programs that use them operate within sRGB only or are unmanaged and display referred, hence them only really working as described above in that space.<sup>1</sup>

### My opinions on implementation

So where does that leave us?  I agree with all but one of Tory's points against their use, that being; the math _does_ check out when using hex codes _within sRGB_ which will result in accurate transfer of colour data between applications.  It will be obfuscated to the user and unclear at a technical level _how_ it works which is bad design, but it will function as expected.

Because of this I'm _fine_ (though not _happy_) with hex codes being implemented but ideally _only_ when a user is operating within the sRGB / rec709 space!  By allowing their use in other spaces (which as established, is broken) we would only be doing users a disservice as hex codes would be unable to do what the uneducated user would expect hex codes to do, _transfer colour data accurately_.  Hex codes **will not** result in the expected output within rec2020, ACES, or DCI-P3 and by allowing people to even try we are creating problems for them.  I don't _like_ hex codes for all the reasons above but if the math checks out I'm not going to be bummed about their technical implementation, just the semantic problem baggage they bring with them.

Finally, right now _none_ of the math checks out for anything other than sRGB!  The new colour picker is floating point and the UX is better but it still uses QColor which is restricted to the sRGB space and unfortunately not a truly robust system for Natron's use case.  While qt5 allows values over 1, it does so only within the scRGB space, again far from a good colour picking system for digital compositing.  This is best dealt with in a separate issue I'll likely make later once your changes are implemented, but the important thing to note here is that _technically_ because the back end is still the same, while the user has more precision with floating point, the colour picker hasn't gotten much more fully featured or less broken in anything other than sRGB... and thus the only thing adding hex codes will _actually_ break further that isn't already broken is some people's continued bad understanding of digital colour! 🙃

### Footnotes

1. So _technically_ hex codes aren't restricted to only being in sRGB or even containing only 3 values, it's just that is mostly how they are used in most popular graphics programs.  Apple actually does implement hex codes for Display-P3 in their colour picker.  This is not used commonly in other programs that implement hex codes and once again displays the pitfalls of the format, though arguably the same  is true for RGB triplets!  AFAIK this is fine as Display-P3 can be represented as 8-bit integers (I think) however the same is not true for other spaces like ACES which need at least 16 bits of precision to work accurately.  Some hex codes have 4 values and include an alpha channel!

**Comment by qwloh** [comment]
Thank you. This is enlightening. I was confused at first as to why Hex input is not available, but upon understanding the technicalities behind (that is, Hex is a construct specific to the sRGB color space, which is only one of the many color spaces video compositing software deals with), I totally agree that it's best to leave out the Hex input altogether to avoid misleading users.

At the same time, if I may raise an idea just for the sake of discussion, what if this piece of information can be built into the software directly to educate users? For example, we could expose the Hex input box but if users try to input hex codes in color spaces other than sRGB, the input will be disabled and a warning tooltip that explains this very rationale will show up.  

In this way, instead of becoming frustrated, I think most users will be okay as long as they see the reason behind why a feature deviates from their expectation. In fact, some may even be appreciative that the limit in their prior understanding is pointed out to them (at least speaking for myself). And I think this is a win-win for both better UX and respecting the technicalities of color management. 🤓

**Comment by devernay** [comment]
What do you propose in terms of UI? I don't think hex codes should be visible, but there could be a way of entering them. For example, by typing # followed by a hex code in a color parameter text boxes. Or a menu entry in the right click menu...

**Comment by Shrinks99** [comment]
Assuming the app can be aware when an sEGB EOTF is used in the viewer, I'd handle this with a hex code text field in the colour picker that gets disabled when a non-sRGB space is used.  I'd also add a tooltip to the field explaining that this is the case.

**Comment by qwloh** [comment]
What @Shrinks99  just described aligns well with what I have in mind.

@Shrinks99 Awesome! I happen to have some free time, could you use my help? I'm thinking since this is probably too complex as a first-timer task, I could help change Natron's slider to the more Nuke-like version in your [Figma mockup](https://www.figma.com/file/HrsTvhVXzZhtAud6GMNEYD/Natron-App-UI-Redesign?type=design&node-id=817-4398&mode=design&t=Q50JoA3IS3NNcHkr-0) (I came across that when browsing other UI/UX-related issues, love that, btw) as a way to familiarize myself with the code in the properties panel first. Then, I can attempt this if it hasn't already been done. Should I go ahead?

Otherwise, thanks everyone for the hard work! Staying excited for Natron as an end user.
