### ISSUE TITLE
Color Selector (replace QColorDialog)

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#201]
_From @nicholascarroll on April 1, 2017 17:34_

## Problem
In Linux the colour dialog is square and shows 8 bit RGB numerical controls. It is difficult to work with that because the viewer shows RGB values in floating.

Also, it would be nice if it were a colour wheel instead of a square.

![screenshot from 2017-04-01 12-16-10](https://cloud.githubusercontent.com/assets/1062708/24580824/061f8404-16d5-11e7-826c-adce45b25c88.png)

**Expected behavior:** 
show floating values  for R,G,B controls in the picker.

**Actual behavior:**
It shows 8 bit, and you have to figure out what value that is. In a *Roto* node, there is no colour picker dropper thingo so it is quite time consuming to get that colour.

### Versions
Natron 2.x
Ubuntu 16.04

_Copied from original issue: MrKepzie/Natron#1592_

**Comment by devernay** [comment]
_From @MrKepzie on April 1, 2017 17:37_

Well it's the native Qt dialog, we didn't get time to come up with a better one. A repository https://github.com/azerupi/NatronColorSelector  was started by @azerupi to provide proper color selectors for Natron but he never got time to make it. 
We are too much hands in the engine right now to get anything done on the gui. 
However If you want to contribute to the NatronColorSelector repo we would gladly then integrate it in Natron.

**Comment by devernay** [comment]
_From @nicholascarroll on April 2, 2017 4:29_

OK I will do that.

**Comment by devernay** [comment]
_From @nicholascarroll on May 6, 2017 20:42_

OK I  was able to put together a proposed design. It uses the triangle HSV wheel like in Gimp and Krita. Here is a screenshot. 
![colorpickerdesign](https://cloud.githubusercontent.com/assets/1062708/25775699/bd88c3b0-3270-11e7-87d2-2c0473ce90d8.png)

It is using this toolkit
https://github.com/mbasaglia/Qt-Color-Widgets
I suggest this design instead of the earlier one by @azerupi because the triangle shows a larger visual area where you see all variations of saturation and luminance as you turn the hue dial.

This is as far as I can take this because I don't know C++ or QT. But I suppose it is fairly simple to code it for someone who does know these.

**Comment by devernay** [comment]
_From @nicholascarroll on May 7, 2017 21:55_

The widget is GPL 3 but comes with a special exception to allow it to go in a GPL 2 codebase:
https://github.com/mbasaglia/Qt-Color-Widgets/blob/master/LICENSE-EXCEPTION
This is the [standard GNU Classpath Exception](https://www.gnu.org/software/classpath/license.html). @MrKepzie is this license going to be OK for Natron? Also, everybody, does the design look good? 

If nobody builds this soon, well I am reading a QT book and will probably have a go at building it sometime.

**Comment by devernay** [comment]
_From @sozap on July 2, 2017 20:41_

Hey,
It's nice to see this tackled !
Everything from the original is there except custom colors, but that's may not be needed...
Here is my design thoughts , I guess everything isn't necessary , it's already better than what we have.

- why two colors at the bottom of the wheel ? ( black and red ) if it's old value vs new one it's ok...
- is it possible to show colors inside the ramps ? R -> a red ramp...
- what about having value ranging from -1 to 1 instead of 0 / 1 , when that makes sense ?

It would be great to have longer ramps (to have more fine tune) but that would mess the clean organisation that we have here... Maybe a more vertical one, like in Nuke IIRC...

Anyways that's just suggestions , I don't see anything that must be done, only suggestions...

Thanks a lot !

**Comment by devernay** [comment]
_From @nicholascarroll on July 3, 2017 15:21_

why two colors at the bottom of the wheel ? ( black and red ) if it's old value vs new one it's ok...
> yes before and after

is it possible to show colors inside the ramps ? R -> a red ramp...
> yes they will show. the screenshot is only the layout in QT Designer

what about having value ranging from -1 to 1 instead of 0 / 1 , when that makes sense
> please elaborate

I chose horizontal sliders to fit the numerical field in nicely. fine tuning will be good however i am just wanting to start with the basics: float instead of 8 bit and a wheel instead of a square. 

@MrKepzie , @devernay are you OK about the license?

**Comment by devernay** [comment]
See also suggestions in diplicate issue https://github.com/NatronGitHub/Natron/issues/80

**Comment by rodlie** [comment]
I guess nobody finished anything related to this? 

I took the regular QColorDialog and added a color triangle from Qt (solutions), at least better than what we have(?)
![newColorDialog](https://user-images.githubusercontent.com/34516798/60110319-33a19380-976c-11e9-8d67-1e56baf73494.png)

**Comment by nicholascarroll** [comment]
Hey that's great @rodlie ! No, I never completed it. I think it is a good enough solution.

**Comment by rodlie** [comment]
I'm also playing around with color wheel popups:
https://youtu.be/UvaOg1rhlmY

Will add some sliders etc (just started).

**Comment by rodlie** [comment]
I decided to make a color selector popup instead as it makes more sense from a UX perspective, test builds can be found at https://github.com/rodlie/Natron/releases/tag/ColorSelectorV1

Unsure if this is something to add in RB-2.4 or wait until RB-2.5?

**Comment by devernay** [comment]
Nice!
It could go to 2.4, since the current color selection dialog is crap anyway, but how difficult would it be to add these:
- it would be nice to have RGB sliders, maybe just a toggle button (I would say a push toggle rather than a radio?) that switches the labels and the underlying logic for the three sliders
- gimme an alpha slider
- HSV as displayed is on gamma-2.2-compressed R'G'B' values. It would be nice to be able to toggle between these and HSV values corresponding to linear RGB values. I would say it's better to use linear RGB values as the default, since this is what the RGBtoHSV and HSVtoRGB plugins do. Let's say you have a way to get R'G'B' from the graphic triangle, then you would convert to linear RGB, and then apply the HSV formula on these to get the values. To go the other way round when using linear HSV, convert to linear RGB, then R'G'B', then HSV from R'G'B' to uppdate the graphic position
- same for RGB values: they should be displayed as linear by default.
- remove the old color dialog button
- if I ctrl-click (command-click) on the colored triangle, this would popup the "old" color selection dialog (it's included in Qt anyway)

**Comment by rodlie** [comment]
Sure, I can expand the widget.

**Comment by rodlie** [comment]
Some progress:
![NatronColorSelector-01](https://user-images.githubusercontent.com/34516798/122116781-4ebcb080-ce26-11eb-87cd-a8e262082453.png)

* Added R, G, B, A widgets
* Color values should be correct

Will continue tomorrow (or when I get the time). Need to figure out how to switch between RGB/HSV widgets (a dropdown makes sense) and some other minor things.

**Comment by devernay** [comment]
I think something like the "4" button (toggle-pushbutton, I don't know the exact name).
It could also only show RGBA sliders when in RGB mode and HSVA when in HSV mode, is space is precious.

**Comment by rodlie** [comment]
Ok, will try out a couple of things to switch mode (RGB/HSV). Should probably also save the mode when changed and restore it on init.

**Comment by devernay** [comment]
or maybe it's not super useful to make that switch.
here's how it is displayed in gimp:
<img width="407" alt="image" src="https://user-images.githubusercontent.com/3778071/122285990-3ab79400-cea4-11eb-8464-dc56622169d4.png">

can you make a PR ASAP with this code?

**Comment by rodlie** [comment]
We could probably just drop the switch.

> can you make a PR ASAP with this code?

I would prefer to get an extra day on this, as I didn't get much time to do anything today, and it's getting late here.

**Comment by Shrinks99** [comment]
From our Discord conversation on this (because chat is a bad place to keep discussions to come back to):

Here's my pitch for layout of @rodlie's new colour widget:

<img width="1087" alt="Screen_Shot_2021-06-16_at_9 29 48_PM" src="https://user-images.githubusercontent.com/5672810/122317951-521a6f80-ceec-11eb-9ed8-0bd31ba861c1.png">

I know the colour wheel can't really go in the margin like that without some further refactoring and obviously this mockup uses different styling — don't worry about any of that too much and if this is decided to be a good direction to go in just adapt it as best you can?

In this mode RGBA is displayed with sliders, HSV is intended to be picked using the wheel.  There are no sliders for HSV because we're already exposing another graphical method of controlling those values, having two modes for that is kind of redundant, especially when the nicer visual one exists.  Also these values can't be keyed right now so they just live up at the top as numbers in case people want to input specific ones.  Users still have all the flexibility that comes with Natron's numerical inputs (scrolling to change exact values, all that good stuff).

This screenshot showcases the widget operating in the triangle mode, 4 colour mode would be unchanged, the colour picker box remains but is now on the right side instead of in between which is where it currently is.  Both buttons in the middle relate to changing the operation of the colour widget, the white box is last because it serves a separate purpose.  I have also removed the r, g, b, & a labels from the colour boxes because they are coloured but have kept them on the h, s, & v boxes because they aren't.

I know that you've got it as a separate popup right now (which is better than the current window!) but still think the in-window contols are the most ideal option because it reduces the amount of clicks that are required to make these which will need to be done multiple times before users get it right.  If space is deemed an issue, note that users should be able to just hit the "4 button" (whatever its actual name is lol) to collapse this down to one line once users are done making colour adjustments.

**Comment by rodlie** [comment]
> Here's my pitch for layout

This is the widget or everything (the RGBA knob + color selector widget)? I have/had no plans modifying the actual ColorKnob.

> There are no sliders for HSV because we're already exposing another graphical method of controlling those values

I do prefer to have sliders for HSV (sometimes).

> I know that you've got it as a separate popup right now (which is better than the current window!) but still think the in-window contols are the most ideal option because it reduces the amount of clicks that are required to make these which will need to be done multiple times before users get it right.

Agree and disagree :)

in-window controls imply that they are part of the ColorKnob and can be adjusted in the same way as other knobs (keyframes etc). This is primarily a replacement for the dialog.

The knob layout in itself also don't support adding widget vertically, I did modify that in an earlier test build (that you have tested), but it broke other knobs. And I don't want to make major changes to core functions (at least not now).


I'm open for all suggestions, but we (all) need to agree on something. I would like to have this (code) finished by the end of this weekend.

**Comment by Shrinks99** [comment]
> in-window controls imply that they are part of the ColorKnob and can be adjusted in the same way as other knobs (keyframes etc).

Agreed.  This is a bit of a challenge, you'd have to create a system of locking some parameters when a user sets keyframes on others for it to work.  Making this into a popup where the values aren't "real" knobs also means you can change the hue slider to degrees later without breaking anyone's files. ;P

Taking that into account, what you have above looks good to me then. 👍  Perhaps modifying the color knob could be looked at in the future, I still think it would offer a better user experience.  As an iterative update this is worlds ahead so as a user I'm happy!

**Comment by rodlie** [comment]
My current implementation of the mock-up by Shrinks99:

![NatronColorSelector-03](https://user-images.githubusercontent.com/34516798/122456252-a20d3b00-cfad-11eb-8d4d-6fed11938477.png)

**Comment by rodlie** [comment]
Did a test build for Mac/Win:
https://github.com/rodlie/Natron/releases/tag/ColorSelectorV2
https://github.com/rodlie/Natron/commits/RB-2.4-ColorSelector

If there are no objections I will do a PR.

**Comment by Shrinks99** [comment]
Would be nice to unify the colour input boxes so that they look the same inside the RGBA knob.  Other than that the new UI looks good to me!

This colour picker still cannot accept values over 1, it only works within a fixed domain.  If this is another thing to address in an eventual update to the color knob and not in this overhaul of the picker I guess that's fine, I seem to remember this being QT4 related?  If you're going to add hex codes they _at least_ need a tooltip briefly explaining their caveats.
![Screenshot 2021-06-21 160921](https://user-images.githubusercontent.com/5672810/122821884-62936700-d2ab-11eb-8994-ed175bb5f6f2.png)

**Comment by rodlie** [comment]
> Would be nice to unify the colour input boxes so that they look the same inside the RGBA knob.

Change the border color on h, s, v, hex?

> This colour picker still cannot accept values over 1, it only works within a fixed domain.

The triangle requires QColor and QColor only supports 0-1. This has been fixed in Qt 5.14+ (https://doc.qt.io/qt-5/qcolor.html#the-extended-rgb-color-model).

**Comment by Shrinks99** [comment]
> Change the border color on h, s, v, hex?

Naw, I think those are fine (they just look like regular input boxes).  I'm referring to the RGB inputs, everywhere else they just have border on the bottom with the colour but the new inputs have the colour for the entire border.  If we're going to roll with the border colour for the future maybe all the existing RGB inputs can get styled like the new ones here?

> This has been fixed in Qt 5.14+.

Thought so, hopefully this one fixes itself! ;)  EDIT: Oh gross, it uses scRGB???  Extremely wack.

**Comment by rodlie** [comment]
> 'm referring to the RGB inputs, everywhere else they just have border on the bottom with the colour but the new inputs have the colour for the entire border.

They are not the same, so I have no problems with them looking a bit different. Since we don't have labels it's even more important to emphasize each color.

only with border at the bottom:
![border-color](https://user-images.githubusercontent.com/34516798/122827735-08af9300-d2e5-11eb-8ca6-ed9b278777cd.png)
vs
![border-color2](https://user-images.githubusercontent.com/34516798/122828184-9be8c880-d2e5-11eb-97ef-5f6b9d7fc717.png)

IMHO it looks better with all border color.

**Comment by Shrinks99** [comment]
I agree, that's why I'm suggesting that the all border color styling be expanded to the other inputs as well.  You're right that they technically represent different things (one is open domain and keyable, the other is not) but at the end of the day I think users will see them as the same thing?  Maybe that's an issue for the current implementation so if you think they're better different then keep them as is.

**Comment by rodlie** [comment]
So, did some adjustments:

https://user-images.githubusercontent.com/34516798/123712342-707c5580-d872-11eb-9205-f720b408ddb2.mp4

Better? change something? go back to previous version?

**Comment by devernay** [comment]
Looks cool! Just one question (I haven't tested it); how does it work when the window is already at the screen's right edge?

**Comment by Shrinks99** [comment]
> Looks cool! Just one question (I haven't tested it); how does it work when the window is already at the screen's right edge?

It doesn't cut off or do anything dumb, just nicely aligns itself to the edge of the window / screen.
![Screenshot 2021-06-28 200413](https://user-images.githubusercontent.com/5672810/123718054-31d3a480-d84c-11eb-9f8c-4828abe66856.png)

**Comment by rodlie** [comment]
Qt takes care of the popup position, so it will align itself properly.

**Comment by rodlie** [comment]
Mac/Win test builds: https://github.com/rodlie/Natron/releases/tag/ColorSelectorV3

**Comment by devernay** [comment]
Looks good! PR?

**Comment by rodlie** [comment]
Sure, will do after work.
