### ISSUE TITLE
Can only write RGBA and RGB components images

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#208]
@rodlie can you please send me an email? (not urgent)

**Comment by listlfa** [comment]
As this issue is still Open I'll contribute. Just installed Natron on Win 7 and see this error immediately.  Following this tutorial of a moving rectangle https://www.youtube.com/watch?v=-5bbzxmKTSo

I see there's no RBG in Show Avail, but don't know how to fix that :)

![image](https://user-images.githubusercontent.com/7302406/82122187-a2447100-97c4-11ea-85cc-2014371d6359.png)

**Comment by devernay** [comment]
@listlfa attach a simple graph showing the problem. Also, you may want to test with 2.3.15RC

**Comment by thima2017** [comment]
I'm new in Natron and I faced this issue too. I was trying to write Card3d node output to mp4 file. I still haven't found a clear regularity, but this is what I tried to solve it and seems it works:
1) I turned on Preferences -> Threading -> Render in a separate process
2) I added a "Color Correct" node before Writer node and then I selected in "Output layer" list ("Color Correct" node preferences) New -> Set RGBA -> typed a name (RGBA) in the top textbox -> OK. And then I selected the new created "Output Layer". In my case it's named RGBA.RGBA. When I select Color.RGBA instead of "RGBA.RGBA" rendering hangs up.
![2020-11-13-220046_1079x803_scrot](https://user-images.githubusercontent.com/32433505/99111735-b34c2e80-25fd-11eb-98aa-70d9dcbcb391.png)
![2020-11-13-220240_900x600_scrot](https://user-images.githubusercontent.com/32433505/99111794-c7902b80-25fd-11eb-930d-862b5cf6a794.png)
Also I have enabled "Copy input image before rendering any plugin" in Preferences -> Rendering. I'm not sure it is helping.
![2020-11-13-220357_900x600_scrot](https://user-images.githubusercontent.com/32433505/99111932-fc03e780-25fd-11eb-8b56-63805d117ebe.png)

**Comment by thima2017** [comment]
I'm using [Natron 2.3.16 beta1](https://github.com/NatronGitHub/Natron/releases/tag/v2.3.16-beta1) and Ubuntu 20.04.

**Comment by devernay** [comment]
@thima2017 can you share a sample project? (you can replace image inputs with colorwheel or colorbars nodes)

**Comment by MiMillieuh** [comment]
Nothing new ? I have the same issue on Natron 2.40 on Fedora : The flatpak works but can't use a text node cause it crashes

**Comment by devernay** [comment]
do not use the flatpak. only use builds distributed through this github(beta builds are ok).

if you have this issue, and since we don't have it, read the messages above where i ask for a sample project. if you post a sample project that exhibits the issue with the natron 2.4.0 binaries, there are 100x more chances to see it fixed

**Comment by MiMillieuh** [comment]
> do not use the flatpak. only use builds distributed through this github(beta builds are ok).
> 
> if you have this issue, and since we don't have it, read the messages above where i ask for a sample project. if you post a sample project that exhibits the issue with the natron 2.4.0 binaries, there are 100x more chances to see it fixed

[bug.zip](https://github.com/NatronGitHub/Natron/files/6978788/bug.zip)

Yeah the text works fine in the non flatpak build... Here a project that doesn't work

**Comment by rodlie** [comment]
add a crop before write (or after transform).

**Comment by MiMillieuh** [comment]
> add a crop before write (or after transform).

The render works but render only the first frame in a tiny file : no errors in Natron


https://user-images.githubusercontent.com/52078885/129425914-00b000ec-fc0d-4105-86b8-619cc5747e2a.mp4

**Comment by rodlie** [comment]
Did you remove `#` from the file name? `#` indicates that you want to write an image sequence, something not possible with a video file.

**Comment by devernay** [comment]
@rodlie good catch, we should not expand #, 
 or we should check for it in writeffmpeg

**Comment by MiMillieuh** [comment]
> @rodlie good catch, we should not expand #,
> or we should check for it in writeffmpeg

It still output one frame like the one before...

**Comment by devernay** [comment]
This issue is solved.
For issues with filename containing #, see https://github.com/NatronGitHub/Natron/issues/693
