### ISSUE TITLE
Missing or Updated Nodes?

### ISSUE THREAD

**Issue by unkerjay** [NatronGitHub/Natron#260]
[neon_v01.ntp.zip](https://github.com/NatronGitHub/Natron/files/1958913/neon_v01.ntp.zip)

This file from this tutorial (download):

https://www.youtube.com/watch?v=nMKegfYRii0

from 2016.

Spits out errors of missing nodes when I open it.

Like a lot of other node based tools, the end project is only as good as the extent to which it is using  existing (current) nodes.

Same thing with blender's Animation Nodes which is in perpetual WIP mode.

Maybe it's something else.  I don't know.  I just started using it and I'm learning.

Perhaps I shouldn't be using two year old tutorials?

Current tutorials haven't been easy to come by.

Not that they're not out there.

So, is it missing or updated nodes or something else?

**Comment by devernay** [comment]
This project was built using Natron 2.0.5 (open the ntp with a text editor to see that at the top), which can be downloaded from https://sourceforge.net/projects/natron/ , but it still runs with the latest Natron (2.3.10 as of this writing), despite the warnings when first opening the project file.

To make the project work, you will need to download the wall-769963_1920.jpg texture from anywhere (eg https://mycovenanthomes.com/wp-content/uploads/2016/01/wall-769963_1920.jpg) , save it in the same dir as neon_v01.ntp, and in the read node change the filename from "H:/Youtube/neon text/wall-769963_1920.jpg" to "[Project]/wall-769963_1920.jpg"

During the development of Natron, we care a *lot* about backward compatibility. Most our unit tests use projects created with Natron 2.0.5, so that we know early when something breaks on that side.

**Comment by unkerjay** [comment]
I've downloaded the wall.

I don't see a Shuffle2 node that reports out errors.

And, even if I get all that sorted out, there's still where and how to
apply the write node.

I've read what you wrote elsewhere in reply to this problem I'm having.

Since others are understanding it and figuring it out, I don't think it's a
problem with the software
as much as my comprehension.

But, without an accurate understanding, I'm dead on anything but the
simplest of designs.

On Mon, Apr 30, 2018 at 6:23 AM, Frédéric Devernay <notifications@github.com

**Comment by devernay** [comment]
To render the images, there is a "Render" button in the parameter panel of the write node, or use the "Render" menu.
If you get lost in Natron, you can also follow basic Nuke tutorials, or read the Nuke documentation: the usage for 2D compositing is very close.

**Comment by unkerjay** [comment]
I'm going to look at the Nuke tutorials and documentation.

Here's the Neon file.

I changed the location of the render to match my system file locations and
hit the "Render" button.

Nothing happened.



On Mon, Apr 30, 2018 at 7:34 AM, Frédéric Devernay <notifications@github.com

**Comment by devernay** [comment]
I think you have to use github's web interface to upload the file.
Here's one that works.

I changed the filename in the Read node to `[Project]/wall-769963_1920.jpg` (always try to use the `[Project]` token in your file names).

I changed the frame range to 1-1 in the project settings, because the output of this project doesn't change with time.

I connected a Write node to Crop2, and set the output filename to `[Project]/neon_out#####.tif`

Hitting the Render button in the write properties panel creates an image in the same directory as the project, called `neon_out00001.tif`

[neon_v02.zip](https://github.com/NatronGitHub/Natron/files/1961425/neon_v02.zip)
