### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by ElDirector** [NatronGitHub/Natron#267]
2.3.10  Windows 10

I read in a shot, connect the viewer, and after a few frames receive the error "Out of memory. InternalDecoderNode failed to allocate memory (23.7 MiB).  Tried this with both tiff and dpx. Just a standard 1080 image sequence, which I've run without issues until now.

**Comment by devernay** [comment]
could you find out which is the last version that works? (2.3.9? .8 .7 .6 .5 .4?)

do you have the same issue with the latest snapshot?

I'm worried, because I don't think I changed anything that could be related to this issue... except I downgraded OpenImageIO from 1.8.6 to 1.7.11. between 2.3.4 and 2.3.5 because of bug https://github.com/OpenImageIO/oiio/issues/1795 <https://github.com/OpenImageIO/oiio/issues/1795>

also right-click in the nodegraph, and select "Display Cache Memory Consumption". Do the numbers grow unreasonably?

**Comment by ElDirector** [comment]
Snapshot is working well

**Comment by devernay** [comment]
Well if the snapshot works, this can be considered closed!
