### ISSUE TITLE
Installer for 2.3.11 blocked by Windows Defender

### ISSUE THREAD

**Issue by eliemichel** [NatronGitHub/Natron#275]
![defender](https://user-images.githubusercontent.com/5802849/40313416-faad3584-5d15-11e8-8982-827377b7f9b6.png)

On my up to date Windows 10 machine, I cannot run the installer for Natron 2.3.11 as it gets blocked by Windows. Even if there are some work around, this might be something to worry about. I don't know the policy followed by Windows to raise this, but it adds an important friction for newcomers.

**Comment by devernay** [comment]
It's probably because applications have to be signed on Windows too. Usually, this involves getting a developper licence, which costs money etc.
We have the same problem on macOS but the workaround is well documented in the Natron documentation.
If you have a workaround, can you contribute a few screenshots that I could include in that doc: http://natron.readthedocs.io/en/rb-2.3/guide/getstarted-installation-windows.html#install

**Comment by devernay** [comment]
Of course, screenshots on an English system would be better (you can temporarilly switch your UI language)

**Comment by rodlie** [comment]
The file might also be flagged as malware etc, this has happened in the past and I had to send the installer to various (anti-virus) companies to get the installer "white listed" on each release.

It's possible to contact Microsoft regarding false positives (if that's the actual problem of course): https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/developer-resources

**Comment by rodlie** [comment]
Not able to replicate on Windows 10 (1909) Pro or Windows 8.1 Pro using 2.3.15RC. If this is still an issue someone would have said something by now(?). Closing issue since we can't do much about it anyway.

**Comment by eliemichel** [comment]
I confirm I can no longer reproduce the issue it must have been fixed somehow!

**Comment by TamerGester** [comment]
Anyone who has this problem can just click the underlined text, then click "Run anyway"

I even got blocked in the first place, when I was downloading the file, by Defender Smartscreen. We can choose to keep the file is this problem occur.

Later if your Natron can't write cache, it's because Defender is blocking it. No notification, but it does. I fixed that by running Natron as administrator.

As long as you download Natron from this place, it should be safe running as administrator.

**Comment by rodlie** [comment]
@eliemichel Great, thanks for the feedback :)

@lehuan5062: I don't recommend running as admin, but if that's your only option....

A small article about the issue: https://getimageview.net/2020/06/02/microsoft-defender-smartscreen-is-hurting-independent-developers/

Btw, this must be a setting or something. With a clean install (ISO from Microsoft) I never get this, on anything.
