### ISSUE TITLE
natron crash when saving

### ISSUE THREAD

**Issue by groslaine** [NatronGitHub/Natron#280]
Natron is constansly slowing a lot when saving the project, it someting crash.
The issue is there since at least 4 version (2.3.12, 2.3.11, 2.3.10, 2.3.9 and maybe more)

I have a ASUS g752 with windows 10

**Comment by devernay** [comment]
Probably all versions are affected, it just depends on the complexity of your project! What's the size of the ntp file? This will give me an idea.
The main limiting factor is RAM. Buy more, or get another computer.
Sorry, but nothing has changed on that side since version 2.0, so I'll have to close this.
Natron 3 was bringing much smaller project files and faster reading/writing, but never got stable enough to be released (source code is in the git, though).
