### ISSUE TITLE
HSVL : V reporting incorrect data in the viewer?

### ISSUE THREAD

**Issue by troywilliams1** [NatronGitHub/Natron#286]
### Problem

The V data being reported in the Viewer window when sampling using Ctrl+LMB appears to be incorrect. 

**Expected behavior:** The reported V data should equal whatever the highest RGB value being reported is.

**Actual behavior:** The number being reported is not a value that reflects any known information.

### Steps to Reproduce

1. Create New project
2. In the node graph add a new node (constant)
3. Set color of the 'constant' to 118, 118, 118 using the color tool
4. Ctrl+LMB in the viewport
5. The data being reported in the V: section of the viewport information is .46, this should be .18116 based on the color information. 

### Versions
This software was compiled from the source code branch tags/2.3.12 at version 266fb27 using GNU C++ version 7.3.0 with OpenMP 4.5 targetting Intel x86-64 for Unix Environment.
The bundled openfx-io plugins were compiled from version 83cd498.
The bundled openfx-misc plugins were compiled from version f03c6c0.
The bundled openfx-arena plugins were compiled from version 50f9e12.
The bundled openfx-gmic plugins were compiled from version 36a4f22.

Windows 10 Enterprise 64-bit 

![image](https://user-images.githubusercontent.com/18218357/41130232-597ae300-6a7b-11e8-9977-2c48ccb4bcb5.png)

**Comment by devernay** [comment]
There is no reference stating that HSV should be computed from linearized color values. The thing is, Nuke until Nuke 8 computed HSV from sRGB values, which made sense since many peaple were using those values to compute HSV in the 8-bit era.
However, let's look back at the original paper by Alvy Ray Smith describing HSV and HSL, presented at SIGGRAPH 1978.
He says: "We shall assume that an RGB monitor is a linear device"
Maybe that's what the Foundry did (reading this paper) when they fixed it in Nuke 9.
Note that in this paper, L from HSL is the luminance and is computed using the NTSC coefficients.

References:

- http://www.icst.pku.edu.cn/F/course/ImageProcessing/2018/resource/Color78.pdf
- https://en.wikipedia.org/wiki/HSL_and_HSV
