### ISSUE TITLE
Viewer freeze when tracking

### ISSUE THREAD

**Issue by bakter** [NatronGitHub/Natron#299]
Hi,

The viewer is constantly freezes, when I build this graph:
https://pastebin.com/F5mG5N8D

App version: Natron 2.3.14
OS: Gentoo
Vid: Nvidia Gtx770

Off:
I'm a heavy Nuke user, I'm interested in Natron, but I can't use it, unstable and missing a lot of important 'small' feature.
Levente

**Comment by devernay** [comment]
Try these: https://natron.readthedocs.io/en/rb-2.3/guide/getstarted-troubleshooting.html

**Comment by devernay** [comment]
I cannot read your ntp file, please zip it and attach it to the github issue

**Comment by bakter** [comment]
I attach the test scene:
[testing_naton.zip](https://github.com/NatronGitHub/Natron/files/2289229/testing_naton.zip)

1. delete the track1 
2. create a new tracker, place it to the deleted tracker pos
3. push trackFW button

The bug is not always reproducible. It may be necessary to try several times.

**Comment by devernay** [comment]
this may be fixed in the latest 2.3.15 release candidates, can you test again? what OS are you using for testing?

**Comment by devernay** [comment]
may be related to #240

**Comment by YakoYakoYokuYoku** [comment]
This is produced by a failed assertion in `Engine/TrackerNodeInteract.cpp`, thing is that certain build configurations may either abort (resulting in a freeze) or segfault (crashing Natron completely), for example

```
* thread #1, name = 'Natron', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
    frame #0: 0x00007ffff64e4b9a libNatronEngine.so`Natron::TrackerNodeInteract::onTrackNextClicked(this=0x0000555556676d10) at TrackerNodeInteract.cpp:254:39
   251      OverlaySupport* overlay = _p->publicInterface->getCurrentViewportForOverlays();
   252 
   253      assert(overlay);
-> 254      ViewerInstance* viewer = overlay->getInternalViewerNode();
   255      assert(viewer);
   256      int startFrame = viewer->getTimeline()->currentFrame();
   257      TrackerContextPtr ctx = getContext();
```

For every button slot in the tracker interactor when signaled its tracker node is requested for an overlay, but this is a null pointer by default so it results in one of the above scenarios. When the node is connected to a viewer or it's in its path then it gains a valid pointer and it remains there even after being removed from an active viewer.

So there are solutions for this, at least I'll name two of them. First is that every slot could return immediately when the overlay pointer is null. Second is that every tracker node should be provided with an overlay on creation. I'm more inclined towards the first because it's the most logical one in my opinion. I'll open a PR for this then.
