### ISSUE TITLE
Detach repo

### ISSUE THREAD

**Issue by rugk** [NatronGitHub/Natron#322]
Maybe you can detach this repo from the not maintained fork?

You can this either [do it manually](https://www.quora.com/Git-revision-control-How-can-one-detach-a-forked-project-in-GitHub#ld_fjxjzo_52503) **or** – which I recommend – just contact the GitHub support to do it for you.

This…
1. shows that this is a real maintained project and not just a repo of someone who (once) made a pull request
2. linking to the original repo on every page does not make sense anymore as it has been discontinued/is not maintained anymore and you…
3. can (and IMHO should) still link to the original repo/website/author/… for crediting them, but you can do so in better ways (in the Readme, wiki or so)
4. it just looks much nicer

**Comment by devernay** [comment]
I have been scratching my head over this a few times... I moved my own repos (openfx, openfx-misc, openfx-supportext) here rather than forking them, but the following repos appear as forks:

- Natron
- openfx-io
- openfx-arena
- openfx-gmic
- openfx-community
- Natron-Tests

I feel bad about breaking from the original repo, but doing so would also bring us a very useful tool for potential developers: the ability to search the source code!

Now that at least one person has asked for it, I would like to hear other people's opinion.

Do you think we should detach this repo from its origin?

**Comment by rugk** [comment]
Well, I've already expressed my opinion, I guess. :smile: 

So the question is maybe, why do you actually want to have it listed as a fork? If it is just to credit some original author, you can just link them in the Readme or more appropriate places, as I said…

**Comment by magdesign** [comment]
+1 for detaching the repo.

**Comment by jeinstei** [comment]
Original authors are already on commits-- and anything related to license should be done in a license-specific manner, anyway. I'd say move the repos to the parent project and have individuals fork. Pull requests can always be done as well.

**Comment by devernay** [comment]
I just posted a request to github support

**Comment by devernay** [comment]
done!
