### ISSUE TITLE
Custom Font on Text Node Issue

### ISSUE THREAD

**Issue by Chadt54** [NatronGitHub/Natron#345]
Natron 2.3.14 CentOS 7

On the Text node when I try to open a .ttf font in the "Custom font" section, nothing happens, it doesn't use the font. Changing the "Font family" works, but not the custom font..

Thank you!

**Comment by Chadt54** [comment]
Nevermind, I didn't realize you needed to then go find the font in the dropdown above that box, and also the font file name was different from the name that shows up in the dropdown (completely different name wtf), so that confused me even further.

It's working now.

**Comment by totymedli** [comment]
This is really confusing. If a custom font is selected it should overwrite the font family option instead of extending it. I had to find this issue to realize how this works. Also, it would be nice if the program could load user installed fonts from system folders like `/usr/local/share/fonts`. Other applications like LibreOffice can handle this.

**Comment by rodlie** [comment]
I will take a look when I get the time, but if I remember correctly there was a reason why I did it like that.

Regarding font folders see ``Resources/etc/fonts/fonts.conf``.

We have (in 2.3.15):
```
<dir>/usr/share/fonts</dir>
<dir>/usr/X11/lib/X11/fonts</dir>
<dir>/usr/X11R6/lib/X11/fonts</dir>
<dir>/usr/share/X11/fonts</dir>
<dir>/usr/local/share/fonts</dir>
<dir>/usr/share/fonts</dir>
<dir>/usr/X11/lib/X11/fonts</dir>
<dir>/usr/X11R6/lib/X11/fonts</dir>
<dir>/usr/share/X11/fonts</dir>
<dir>/usr/local/share/fonts</dir>
<dir prefix="xdg">fonts</dir>
<dir>~/.fonts</dir>
```

**Comment by totymedli** [comment]
I just checked and it can auto load fonts if they are placed into the `/usr/share/fonts/` directory. Just choose the subdirectory for your font type (usually `truetype` for TTFs), create a new directory for each  font family and drop the files (of different weights and styles) into the corresponding ones. This way Natron will recognize the whole font family as one and selecting the weight will apply the proper font.

**Comment by rodlie** [comment]
Great that you got it working.

Regarding the override, I now remember why it's like that, the override accepts a file or a folder. Since the override is added directly to fontconfig, the text generator does not know what you added in the override.

I will update the help text in the Text node to reflect this.

To implement what you want I will need to find out what the ttf you added is called in fontconfig (the real name), should be doable (no ETA).

**Comment by rodlie** [comment]
Fixing the override was easy, **but** this will break older projects that uses an override + system fonts, so it should probably not be added until v2.4(?)

**Comment by totymedli** [comment]
Wow. Thanks for the super fast response. TBH knowing that the fonts are auto-loaded from `/usr/share/fonts/` and that I can add a custom folder directory is enough. The core of the problem was that this information was not presented to me. Out of the box I would expect a custom font attribute to be a single file that overwrites the general font. I wouldn't even expect a directory to work since this is an element level attribute. Adding a whole font directory should be a project level setting, but this is just nitpicking. Updating the helper text perfectly solves the issue.

Thanks for the work you do. This app is amazing. The thing I generally miss the most is more hover help text so I can find out what does what.

**Comment by rodlie** [comment]
> Adding a whole font directory should be a project level setting

The custom font option was meant as a project setting, if you want a portable text project dump the fonts you use in a folder and reference them through [Project]/folder_with_fonts in custom fonts.

**Comment by totymedli** [comment]
Yeah now I get its just not clear from the UI layout.
