### ISSUE TITLE
undo problem

### ISSUE THREAD

**Issue by mapulse** [NatronGitHub/Natron#370]
### Problem
undo issue with Natron version 2.3.14

**Expected behavior:** I wanna undo node settings.
**Actual behavior:** some node disabled undo. Natron was not undo node settings but undo node move or others.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): Natron version 2.3.14 
* **OS version:** Fedora 29 64 bit

**Comment by devernay** [comment]
we need precise steps to reproduce the issue

**Comment by devernay** [comment]
please give more details, or I will have to close the issue

**Comment by berniebernie** [comment]
Same Issue as mapulse.

Node creation works in the undo queue
Node parameters are ignored in the undo queue

Natron version 2.4.3 Release
OS Win10

Screencapture of problem: https://i.imgur.com/9pP3Z0U.gif

**Comment by HeCorr** [comment]
I'm also facing this problem. when moving something with the Transform node's screen controls, Ctrl + Z cannot undo those changes:

https://user-images.githubusercontent.com/75134774/195761123-0a47b801-7ab6-4c8e-a119-883d393b9ee7.mp4

Interestingly, if I keep pressing Ctrl + Z repeatedly, it slowly reverts back to the original position as you can see in the video.

My wild guess is that for each frame that the mouse is being held down, an undo state is being stored instead of only one when the mouse is released.

@devernay can you please reopen the issue? this is a pretty big deal in my opinion. I'm surprised it's still not fixed.

**Comment by devernay** [comment]
hum this is a different problem. can you file a separate issue with a proper title ? ( you can use the same video)
curiously, solving this is more complicated than it seems... but I fully understand your request

**Comment by HeCorr** [comment]
> can you file a separate issue with a proper title ?

sure thing!
