### ISSUE TITLE
using 'dialog.setParamChangedCallback()' makes Natron to quit.

### ISSUE THREAD

**Issue by fabiof17** [NatronGitHub/Natron#379]
### Problem

using 'dialog.setParamChangedCallback()' makes Natron to quit with no warning

### Steps to Reproduce

1. run following code in script window :
```
from NatronEngine import*
from NatronGui import *
from PySide.QtGui import *

def paramChangedCallback():
	if paramName == "myBool":
		myInteger.setVisible(myBoolean.get())

def test():
	app = natron.getGuiInstance(0)
	dialog = app.createModalDialog()

	myInteger = dialog.createIntParam("myInt","Tan integer very important")
	myInteger.setAnimationEnabled(False)
	myInteger.setAddNewLine(False)

	dialog.createBooleanParam("myBool","Yet another important boolean")

	dialog.refreshUserParamsGUI()

	dialog.setParamChangedCallback("paramChangedCallback")
	if dialog.exec_():
		print ('toto')


test()
```
### Versions

* **Natron v2.3.14**
* **Windows 10**

**Comment by devernay** [comment]
Confirmed on macOS. Crash happens when executing the callback, probably because of recursive calls to `PyRun_String()`. It was fixed by taking the Python GIL again (it was removed 4 years ago).

It has probably never worked since february 2015 and commit https://github.com/NatronGitHub/Natron/commit/46d9d616dfebfbb931a79776734e2fa17202f7cb

Also, the doc was wrong for callbacks. I fixed it as well. paramChangedCallback takes 3 arguments. And I'm not sure you can change the visibility of parameters in dialogs (maybe you should use a panel instead, see https://natron.readthedocs.io/en/rb-2.3/devel/callbacks.html ).

It was a tough one, I must say, but it should be OK now, at least it doesn't crash on my system anymore.

Can anyone confirm if it is fixed on Linux and Windows too?

**Comment by fabiof17** [comment]
Hi Frédéric.
Will make a test on both Windows and Linux within a few jours.

Thanks

**Comment by fabiof17** [comment]
I le, after next rele :)

Le dim. 23 juin 2019 à 20:42, Fabrice Fernandez <fabiof17pro@gmail.com> a
écrit :

**Comment by devernay** [comment]
@rodlie can you test it?

**Comment by rodlie** [comment]
code runs fine on Linux using latest RB-2.3
