### ISSUE TITLE
Crop : Extent:"Size" reformat, not really reformat

### ISSUE THREAD

**Issue by chenycallen** [NatronGitHub/Natron#413]
### Problem

About "Crop" reformat,but not really reformat
Or is there another way? (or bug?)😅

![]()
### Steps to Reproduce

1. My input is 1920*7680
2. I use Crop Extent select "SIZE" to cut the middle of the image, then I Enable reformat
3. But still the same size 1920*7680 , no reformat
4. so I need use Crop again Extent select "Format" then I get the format I want.

first crop
![image](https://user-images.githubusercontent.com/30933580/62273616-860f5780-b470-11e9-80d0-a39fa99d8a7c.png)

Second crop (I got really reformat)
![image](https://user-images.githubusercontent.com/30933580/62273649-9c1d1800-b470-11e9-910d-18a40766f3d3.png)

I put 2 sample in sheet ,first crop size is not I crop reformat ,but Second crop is correct.
![image](https://user-images.githubusercontent.com/30933580/62273890-3e3d0000-b471-11e9-8044-c8d9cc024e33.png)

Nuke sample
![image](https://user-images.githubusercontent.com/30933580/62273654-a3442600-b470-11e9-96cd-685aca98ee08.png)

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): Last version
* **OS version:** Window10

**Comment by devernay** [comment]
Thank you for filing this issue.

This is the expected behavior, see the documentation for the "reformat" checkbox (tooltip or online doc)

"Reformat: Translates the bottom left corner of the crop rectangle to be in (0,0). This sets the output format only if ‘Format’ or ‘Project’ is selected as the output Extend. In order to actually change the format of this image stream for other Extent choices, feed the output of this node to a either a NoOp node which sets the proper format, or a Reformat node with the same extent and with ‘Resize Type’ set to None and ‘Center’ unchecked. The reason is that the Crop size may be animated, but the output format can not be animated."

So you have two alternatives (NoOp or Reformat), just pick yours.

Also, please, when you file an issue be more specific that "last version", because the issue may not be solved immediately, so we have to know with which version the bug appeared.
