### ISSUE TITLE
Dev : Gui should need to be rewrite 

### ISSUE THREAD

**Issue by threedslider** [NatronGitHub/Natron#437]
I do not like QT4 it's too much as in french term "usine à gaz" that mean it makes some problem for someone who launch Natron. Certainly I love Gui from Natron but not QT4 system so I ask you it would be good to rewrite Gui in his own without to depend with QT4 or QT5 ?. I propose you to make UI in OpenGL 100% but keeps same visual tools and interface. The advantage of this is compatible, fast and light on most to users who use it and the disadvantage is to rewrite everything and can lead to some bug in development but when all is fixed and finalized no need to worry in the future because it will be solid and expandable.

What do you think on that ?

**Comment by crazyrobinhood** [comment]
The main problem is the OS. In near future for example, apple will stop support opengl in favor of Metal, a proprietary API. Linux will soon switch to Vulkan (which is pretty much opengl5 with a new name and a lower-level of interacton with hardware). I think Linux is tha way to go for the future professional studios. Now someone is still stuck with windows and its huge waste of ram and pretty bad and slow pre-caching due to defects in its structure. ( so you have to buy super expensive hardware just because it seems your pc is old and cannot catch new software, but that's not completely true since the main problem is OS itself.). Try Linux, your life will imporve. :)

**Comment by rodlie** [comment]
I see no reason to drop Qt. The amount of work would be massive, and for what?

**Comment by threedslider** [comment]
Maybe it should be to create two branch one for QT and another for OpenGL... better is more choice :)
Good idea ?

**Comment by rodlie** [comment]
Feel free to fork and modify however you see fit :)

**Comment by threedslider** [comment]
Ok this year i will try to rewrite in Opengl for UI :)

**Comment by rodlie** [comment]
I'm all in for new features etc, but why not help with existing UI issues/features first? We have many to choose from. This will also get you familiar with the code, something needed for this major task.

But don't let me stop you, if you feel like this is something you want to do, go right ahead :)

**Comment by devernay** [comment]
@threedslider hint: in the github issue browser, select "2.3" or "2.4" in the "Milestones" pull-down at the top of the issues list. You'll see there are lots of things to do to improve Natron without fully rewriting the GUI (18 issues left for 2.3, 118 for 2.4).

And actually, after you get to know the code, you'll probably conclude that if you want to get rid of Qt, you'll have to rewrite Natron from scratch. Qt is not only used for the Gui, but also for threading, signal/slots, etc. Almost everything uses Qt (which is not at all a bad framework, and is certainly the most portable one).

**Comment by gdeverlant** [comment]
> Ok this year i will try to rewrite in Opengl for UI :)

How about looking in Blender 2.8 UI to take some inspiration?

**Comment by threedslider** [comment]
@devernay ok i will see that if i can fix some issues. I have created two branch as RB-3.0 and RB-4.0 in my repository, maybe you will need to create too and you will sync my repo in your if you want ?

@gdeverlant Blender 2.8 UI is great, surely it will be a great inspiration :)

**Comment by gdeverlant** [comment]
I think my recommendation would be to create an UI API which is modular. A good example could be imgui, Haxe UI, and other kind of UI Framework.

**Comment by devernay** [comment]
@gdeverlant sure, I'd recommend the same thing for a full rewrite. I think removing Qt from the current code would be too much work, and it's not worth it unless it's a full rewrite: take some inspiration from the existing code, and rewrite everything.
It may even be a god thing to port it to blender and propose an alternative to the current compositor with something more efficient and OpenFX-compatible.

**Comment by gdeverlant** [comment]
This would be really the most amazing thing in essence. Replacing the current crappy video editor in Blender would make the whole thing much better. But the problem with Blender is that the UI code is not a framework and it is intrinsically mixed with the core so your challenge would be to get the UI part of the code ou as a refactoring external API so that it can be plugged in dynamically or used in the future by other projects who want to have a Blender style UI.

My advise would be to really inspire yourself from this UI framework that exist in the Java world with modularity made possible through the use of the OSGi framework which is a dynamic runtime. The UI is backed with JavaFX hooked on top of OSGi and it is amazing.

https://github.com/Drombler/drombler-fx

https://www.drombler.org/drombler-fx/

If you want to really grasp the power of dynamic code swapping I suggest you watch these videos and inspire yourself from OSGi and JavaFx: 

https://www.youtube.com/watch?v=liOFCH5MMKk
https://www.youtube.com/watch?v=y2mvLSzM1kg

This is going to blow your mind and literally bring your coding to a new paradigm...

Once you get the point and can follow the concepts of the framework you would need to hood this up into blender https://github.com/CppMicroServices/CppMicroServices which is the OSGi implementation for C++ world or maybe adapt the code of Natron based on this architecture.

I hope that it helps....

Let's keep in touch I could support you since I'm well versed in the OSGi world.

**Comment by ruchitinfushion** [comment]
Please don't think about removing Qt. QT 6 are coming with big updates. And forget about Blender GUI.

**Comment by wlpha** [comment]
Why not try imgui and switch to various platforms seamlessly

https://github.com/ocornut/imgui

**Comment by al-sabr** [comment]
I think merging this thing into the actual blender 2.91 with an amazing image\video sequencer with node editing would be a win win!

**Comment by Songtech-0912** [comment]
@threedslider We are working on a Qt5 port - see https://discuss.pixls.us/t/current-state-of-development/23852 for details

**Comment by Songtech-0912** [comment]
> I think merging this thing into the actual blender 2.91 with an amazing image\video sequencer with node editing would be a win win!

@al-sabr If you can do it, then feel free to! Natron is open-source after all. Fork your own version of Natron and add it to blender.

**That said, please don't suggest this to the core devs.** There are probably a million reasons why, but a few big ones include:

* Blender and Natron have COMPLETELY different codebases, notwithstanding the fact that Blender is written in C while Natron is C++ with the addition of Boost and Qt, which, when added together, makes Natron's code almost completely incompatible with any C code
* OpenGL is a very different to Qt in a lot of ways - how the UI is drawn is different, how it is structured is different, etc.
* Compositing software is NOT 3D software. Let's make this super clear, those are 2 different things - 3D software helps you to build 3D models, texture them and create 3D environments, compositing is where you integrate 3D renders with live-action footage, motion graphics, or other background footage.
* Blender is big enough already - it doesn't need 200K lines of code to burden it more
* The amount of effort to integrate any 2 software is so great that it takes big companies with hundreds of devs YEARS to be able to get that done. We have 2-ish devs (besides community contributions), do you really think this is possible?

**Comment by Songtech-0912** [comment]
@devernay Sorry to bother, but I recommend this issue to be closed. The question at hand is resolved, and it's clear that there isn't much to discuss further.
