### ISSUE TITLE
Property panels of PyPlug's nodes cannot be closed or fully inspected

### ISSUE THREAD

**Issue by Vhati** [NatronGitHub/Natron#449]
### Problem

A PyPlug's nested nodes are ostensibly locked and inaccessible. Yet they can be double-clicked, creating an unclosable properties panel.

### Steps to Reproduce

* Add a Lightning node.
* In the node properties header bar, click the eye button (5th from the right) to "show the underlying node graph."
* They'll be shown, and the graph will be locked (grayed out).
* Double-click on one of the nested nodes to get its properties. (Yes, that's allowed.)
* Its properties panel will appear. It will not respond to clicks... including the "X" to dismiss it.
* To get rid of the properties, you need to unlock the graph (converting the PyPlug into a regular group) to make the "X" work.

### Versions

Official Natron 2.3.14 on Win 7

**Comment by devernay** [comment]
You can also use the "close all panels" button (white cross in the image below)
<img width="172" alt="image" src="https://user-images.githubusercontent.com/3778071/72215690-5490c280-34cb-11ea-990e-f72567b97dcf.png">

I think it's OK to open these properties panels, in order to inspect the PyPlug's content, but one should be able to:
- select different tabs to inspect these (Controls/Node/Info) - the contents of each tab should be disabled
- click any on the five leftmost buttons in the titlebar (which do not modify the node's properties)
<img width="123" alt="image" src="https://user-images.githubusercontent.com/3778071/72215720-bcdfa400-34cb-11ea-8d94-7bf23f4b9657.png">

**Comment by splidje** [comment]
Where do I get the Lightning node to try this?

**Comment by splidje** [comment]
Actually, I can reproduce this with any PyPlug. Should have tried that before posting before!

**Comment by devernay** [comment]
Yes, use Lightwrap (which is what I did)

**Comment by splidje** [comment]
I believe this fixes it:
https://github.com/NatronGitHub/Natron/pull/452
