### ISSUE TITLE
How do you use Natron?

### ISSUE THREAD

**Issue by contentfree** [NatronGitHub/Natron#457]
My team is looking for an open source replacement for After Effects and we came across Natron. We downloaded and installed. Coming from After Effects, we're less familiar with node-based compositors so naturally we sought out the documentation.

We found the [User Guide](https://natron.readthedocs.io/en/rb-2.3/guide/getstarted.html) however, the most important bits (from this user's perspective) are completely missing. Case in point: [Working with Nodes](https://natron.readthedocs.io/en/rb-2.3/guide/getstarted-environment-nodes.html) and [Animating parameters](https://natron.readthedocs.io/en/rb-2.3/guide/getstarted-environment-anim.html) are both completely empty. It appears that everything explaining the UI is completely empty.

Is there _another_ source for documentation?

**Comment by devernay** [comment]
- visit the Natron forum at https://discuss.pixls.us/c/software/natron and take a look at the sticky posts
- take a Nuke manual, preferably for an older version of Nuke (eg Nuke 6)
- watch YouTube videos/tutorials

**Comment by contentfree** [comment]
Thanks for the suggestions. I suggest adding them to the introduction of the environment part of the User Guide for other newbs.

**Comment by hellocatfood** [comment]
@contentfree there's also a lot of tutorials here https://www.youtube.com/playlist?list=PLprXrT2oteICaZqvsrMQJHy4xIjkqqThH

**Comment by JonTAllen** [comment]
@hellocatfood @devernay It may help others if there is a completed user guide so people don't have to keep searching the forums and sticky posts. Doing this would also make to make the experience more user friendly. It would also prevent other potential users from asking either of you, or anyone else on your team, from getting such questions over and over again. That way you can focus that much more of your time on improving the software. As the GIMP software developers have learned it is sometimes best to go with what people want; in this case easier access to centralized user manuals, instead of hunting the forums. Here is the relevant article from GIMP project: https://www.gimp.org/news/2020/01/04/gimp-and-gegl-in-2019/ (Read the first five paragraphs specifically.)

**Comment by LesterCovax** [comment]
If only this software was open-sourced and people could contribute to improving/centralizing the documentation 🤔

**Comment by devernay** [comment]
> If only this software was open-sourced and people could contribute to improving/centralizing the documentation 🤔

huh?
It's not only open-sourced, it's also free software as in "free beer" AND as in "free speech". The full source code AND the documentation is in this repository. Fell free to contribute.

**Comment by hellocatfood** [comment]
> > If only this software was open-sourced and people could contribute to improving/centralizing the documentation thinking
> 
> huh?
> It's not only open-sourced, it's also free software as in "free beer" AND as in "free speech". The full source code AND the documentation is in this repository. Fell free to contribute.

I think he was being sarcastic...

**Comment by devernay** [comment]
Yeah right. If only more people could make less "sarcastic" and more "real" contributions...

**Comment by rodlie** [comment]
* https://natron.readthedocs.io/en/rb-2.3/
* https://natron.readthedocs.io/en/rb-2.3/guide/getstarted-troubleshooting.html
* https://discuss.pixls.us/c/software/natron
* http://thefoundry.s3.amazonaws.com/products/nuke/documentation/Nuke_6.1v2_UserGuide.pdf
* https://www.youtube.com/playlist?list=PLqazFFzUAPc7c67ZuC629CBVL-26e_5QE

**Comment by devernay** [comment]
inactive issue. closing
