### ISSUE TITLE
Adding a Retime node causes expressions to cease functioning

### ISSUE THREAD

**Issue by hellocatfood** [NatronGitHub/Natron#476]
**Describe the problem or suggestion here.**
I have a Natron project which uses an expression in the Text node to create a type-writer like effect. It shows a new character every frame. To slow it down (a new character every x frame) I tried adding a Retime node.

**Expected behavior:**
The animation of the Text node should slow down or speed up if I set the retime node to a different value.

**Actual behavior:**
Changing the value on the Retime node cases the animation of the text to stop or behave erratically. This appears to happen on any node that uses an expression.

Sample projects attached.

[expressions_retime.zip](https://github.com/NatronGitHub/Natron/files/4449936/expressions_retime.zip)

### Versions
* **Natron version/commit**
Natron version 2.3.15 Snapshot.
* **OS version:**
Ubuntu 19.10

**Comment by devernay** [comment]
the reason for this issue is that Text has an inifinite TimeDomain. Here it is, compared to Rectangle:
![image](https://user-images.githubusercontent.com/3778071/78801834-00826680-7972-11ea-90af-a8eb948a70e0.png)
![image](https://user-images.githubusercontent.com/3778071/78801851-04ae8400-7972-11ea-9696-d7d56c8ebcd2.png)
Things to check and compare between TextOFX and Rectangle:
- the available plugin contexts (TextOFX doesn't have anything else than the Generator context - all plugins should have a General context available, and I noticed that a few other openfx-arena plugins are missing the General context)
- clip preferences for the input and output

**Comment by rodlie** [comment]
Will take a look tomorrow.

**Comment by devernay** [comment]
You shouldn't need to add a time domain. Rectangle or Constant don't have one

**Comment by rodlie** [comment]
TextOFX don't use GeneratorPlugin from openfx-supportext.

**Comment by devernay** [comment]
@rodlie what is the reason for closing this?

**Comment by rodlie** [comment]
I though this was fixed.

**Comment by devernay** [comment]
This is an issue with the openfx-arena generators, so that's where it should be fixed. Do you now use ofxsGenerator.h in those? Or did you copy GeneratorPlugin::getTimeDomain from https://github.com/NatronGitHub/openfx-supportext/blob/master/ofxsGenerator.cpp#L239

if your plugins can be instantiated in the General context, they should implement getTimeDomain the way it is done in ofxsGenerator.cpp

**Comment by rodlie** [comment]
I just copied GeneratorPlugin::getTimeDomain to the generators.

I was planning to move the generators over to GeneratorPlugin this weekend, probably a better idea in the long run.

**Comment by devernay** [comment]
but can they be instantiated in the General context?
All the Generator should have at least also the General context. The Generator context in openfx is too limiting.

**Comment by rodlie** [comment]
``getContext()`` returns ``eContextGeneral`` here in TextOFX. Will double check others.

**Comment by rodlie** [comment]
``TextOFX`` and ``Texture`` in openfx-arena has eContextGeneral and time domain, they are the only generators in use except for AudioCurve, but that plugin only generates a black image since it not a image generator.

**Comment by devernay** [comment]
can you please check why they behave differently than other generators (eg Constant) in Natron?

**Comment by devernay** [comment]
oh now I see that text has the correct framerange, finally, so this should work fine
<img width="170" alt="image" src="https://user-images.githubusercontent.com/3778071/83952657-fc968780-a7ee-11ea-9390-24d99121607e.png">
I'll test it

**Comment by devernay** [comment]
yes, fixed
