### ISSUE TITLE
Animated Font Family doesn't render

### ISSUE THREAD

**Issue by hellocatfood** [NatronGitHub/Natron#482]
### Problem
Animating the Font Family value of the Text node using an expression shows in preview mode but changes aren't rendered.

**Expected behavior:**
Each frame of an animation should have text rendered using a different font.

**Actual behavior:**
Only the first font is used on each frame

### Steps to Reproduce
I’ve been trying to recreate something like the intro sequence to the Enter the Void film. See it below from approx 01:10 (warning: flashing images):
https://www.youtube.com/watch?v=wNtxgxYY7sI

I entered the following expression into the Font Family value of the Text node
```
if frame >= 0:
	Text1.name.set(frame)

ret=Text1.name.get()
```

When I press play the Font Family value and font displayed in the preview updates each frame. However, when I try to render it just the first font for each frame.

Project file attached
[animated_font.zip](https://github.com/NatronGitHub/Natron/files/4518141/animated_font.zip)

### Versions

* **Natron version/commit** 2.3.15
* **OS version:** Ubuntu 19.10

**Comment by devernay** [comment]
@rodlie this is because of this line: https://github.com/NatronGitHub/openfx-arena/blob/master/Text/TextOFX.cpp#L1653

Natron considers that this parameter cannot be animated, and thus does not render a new frame.

Workaround: animate the text, or set an expression for the text (which can simply be "the text"). This will trigger a new render at each frame.

@rodlie Is there a specific reason for not animating this parameter (and many others in openfx-arena)?

Usually, we should only mark as setAnimate(false) parameters that prevent the plugin to work correctly when animated.

**Comment by rodlie** [comment]
I know. There was a reason for it, but I don't remember why.... I will check this weekend.

**Comment by rodlie** [comment]
The ``ChoiceParam`` is dynamic, because of this the actual font name must be stored in a secret ``StringParam``. Animating the ``ChoiceParam`` will not affect the ``StringParam``. I can add an override and get the font name from the ``ChoiceParam`` if it's animated, but then the options keyed (the font name) from the ``ChoiceParam`` can never be guaranteed since it's dynamic (if you load the project on a different computer or alter your fontconfig cache).

**Comment by devernay** [comment]
@rodlie was a fix commited?

**Comment by rodlie** [comment]
I have not changed anything, as said I can enable animation on the ChoiceParam and add an override that uses the value from the ChoiceParam if it's animated, but if any changes happens to the fontconfig cache the result will differ when loading the project. It's not a good solution in my opinion.

A workaround is to use Pango Markup to change the font family, can be done with a simple expression.

**Comment by devernay** [comment]
Can you document the pango markup solution?

**Comment by devernay** [comment]
Or should the secret stringparam be non-secret (visible) and canAnimate?

**Comment by rodlie** [comment]
Sure, that could be an alternative.

**Comment by devernay** [comment]
If it works this way, you should also note in the tooltip for both params that only the string param can be keyed/animated

**Comment by rodlie** [comment]
Will do, I'm currently testing.

**Comment by rodlie** [comment]
Fixed. Animation works and I didn't notice any regressions.
