### ISSUE TITLE
Drag and Drop local file to FileParam field in PyModalDialog from Windows has leading slash

### ISSUE THREAD

**Issue by philomory** [NatronGitHub/Natron#493]
### Problem

On Windows, when you drag and drop a file into a `FileParam` field in a `PyModalDialog` (or indeed any field which is rendered using the LineEdit class), the path to the file is filled into the field in the dialog, but there is a preceding slash added. 

**Expected behavior:** Dragging the file `C:\example.png` into a `FileParam` field should result in the text `C:\example.png` or `C:/example.png` in that field.

**Actual behavior:** Dragging the file `C:\example.png` into a `FileParam` field results in the text `/C:/example.png` in that field.

### Steps to Reproduce

1. Create `initGui.py` with the following contents:
```python
from NatronGui import *

def exampleDialog():
  d = app.createModalDialog()
  d.createFileParam('example','Example')
  d.refreshUserParamsGUI()
  d.exec_()

natron.addMenuCommand('Example/File Dialog','exampleDialog')
```
2. Launch Natron
3. Select Example > File Dialog from the menu
4. Drag a file from your disk to the text field of the file dialog
5. Observe that the field fills in with the path to the file, but there is an extraneous leading slash that makes the path invalid.

Screenshot after dragging in `C:\example.png`:
![image](https://user-images.githubusercontent.com/200123/82108216-b440e980-96c8-11ea-88f6-78a9c1269a7b.png)

Note that I'm not concerned with the choice of forwards vs backwards slashes within the path, as either of them are valid; it is only the leading slash ahead of the drive label that is problematic.

### Versions

* **Natron version/commit:** Natron-2.3.15-RC20
* **OS version:** Windows 10

**Comment by philomory** [comment]
Actually, it turns out that the _core_ of my problem is that if you drag-and-drop a file into the field, and submit the dialog without taking any other actions, the resulting value of the param is the empty string, rather than what the value displayed in the UI; I'll create a separate issue for that.

**Comment by rodlie** [comment]
drag-and-drop files on lineedit seems broken in general on Windows, any file dropped on params results in a leading slash.

**Comment by devernay** [comment]
@rodlie it seems like replacing .path() with .toLocalFile() should fix this, instead of the patch you proposed in #497 , can you check please?

If yes, then we should also:

- change `bookmarks[i].path();` to `QtCompat::toLocalFileUrlFixed(bookmarks[i]).toLocalFile()` here: https://github.com/NatronGitHub/Natron/blob/RB-2.3/Gui/SequenceFileDialog.cpp#L732
- remove the code here: https://github.com/NatronGitHub/Natron/blob/RB-2.3/Gui/SequenceFileDialog.cpp#L735
- change `url.path();` to `QtCompat::toLocalFileUrlFixed(url).toLocalFile()` here: https://github.com/NatronGitHub/Natron/blob/RB-2.3/Gui/SequenceFileDialog.cpp#L1697
- remove code here: https://github.com/NatronGitHub/Natron/blob/RB-2.3/Gui/SequenceFileDialog.cpp#L1699
- same here: https://github.com/NatronGitHub/Natron/blob/RB-2.3/Gui/SequenceFileDialog.cpp#L2412
- and here: https://github.com/NatronGitHub/Natron/blob/RB-2.3/Gui/SequenceFileDialog.cpp#L2421

- change `url.toLocalFile();` to `QtCompat::toLocalFileUrlFixed(url).toLocalFile()` here: https://github.com/NatronGitHub/Natron/blob/RB-2.3/Gui/SequenceFileDialog.cpp#L1901
- remove the code here: https://github.com/NatronGitHub/Natron/blob/RB-2.3/Gui/SequenceFileDialog.cpp#L1904

**Comment by rodlie** [comment]
Will check when I get home in a couple of hours.

I was wondering why ``path()`` was used, but I didn't have the time to check last week.

**Comment by rodlie** [comment]
Uploaded Windows rc22 builds (``toLocalFile()`` works)
