### ISSUE TITLE
Reformat node does not default to the project's root format

### ISSUE THREAD

**Issue by Shrinks99** [NatronGitHub/Natron#533]
### Problem

In Natron 2.3.15 the reformat node defaults to 640x480 despite the root format being different

**Expected behavior:** It should inherit the root format of the project by default (`getFormatResolution` I think?)

**Actual behavior:** It is 640x480 (`eParamFormatPCVideo`)

### Steps to Reproduce

1. Make sure the project is set to something other than 640x480
2. Tab in a reformat node
3. :(

![natronbug](https://user-images.githubusercontent.com/5672810/89270124-e3e8f900-d608-11ea-86b5-624be9c595e9.gif)

### Versions

* **Natron version/commit:** 2.3.15
* **OS version:** MacOS 10.15.6 / Windows 10, 2004

**Comment by rodlie** [comment]
Looking at the code this is intended behavior, probably a reason for that(?).

**Comment by Shrinks99** [comment]
I can see that it's hardcoded to eParamFormatPCVideo, I just don't think it should be :P

**Comment by devernay** [comment]
actually, there was a logic to set it from the project format, which was broken by https://github.com/NatronGitHub/openfx-misc/commit/e409cac9f - but the code was bad before that commit too, because you shouldn't set values in createInstance

What I propose:
- add Type "To Project" which implements that logic (move the logic from createInstance() to render())
- that choice has to be last in the list for backward compatibility
- increment the plugin minor version
- set the default value to "To Format" if plugin is instanciated with major.minor < new version, else set it to "To Project" - not sure it will work

Does that look ok?

**Comment by Shrinks99** [comment]
Should probably be labeled `Output Format 1920x1080` (example resolution of course) as that's what is being used in the settings UI label to keep things consistent.  Alternately just set it as the actual output format name instead of "Output Format", both are good options, I suspect number 2 is less work.

Another good small UX fix that will make things faster! :D

**Comment by devernay** [comment]
I prefer Project Format, because Output Format may refer to the output format of anything (you can have writers in any format), but there's only one Project Format.

The size may not be in the menu, because then if you change the project format the menu should change too, and that's not possible in OpenFX.

**Comment by devernay** [comment]
Anyway the actual size will always be visible in the Viewer

**Comment by Shrinks99** [comment]
I agree that "Project Format" is a better name both in this node and in the project settings (for most VFX work this is also the size of your _input_ format), perhaps "Output Format" should be renamed.  It's worth noting that this value is also named `outputFormat`.

<img width="307" alt="Screen Shot 2021-03-25 at 1 44 52 AM" src="https://user-images.githubusercontent.com/5672810/112425050-ce495080-8d0b-11eb-9838-9feee20d4759.png">

**Comment by devernay** [comment]
The script name will have to remain as it is, unfortunately, but we can change the label and the doc.
Nuke calls it the "root" format.
I think in the project settings, it still makes sense to call it the output format, since it's the default format for writers, whereas readers have the format of the sequence or image they read.

**Comment by Shrinks99** [comment]
If it's being referred to elsewhere as the project format it should have a matching label.  Giving the same parameter multiple labels introduces the potential for confusion.  Would be in favour of switching to "Project Format" everywhere it is used or referred to.  In writers it's already referred to as project format!

**Comment by devernay** [comment]
well there's only one format for the project so "Project Format" matches "Project Output Format", isn't it? just like "Fred's Car" matches "Fred's Nice Car", since Fred only has one car.

**Comment by Shrinks99** [comment]
It doesn't match though, they are currently different names names.  If I set value "Fred's Nice Car" to 1 why would I expect the value for "Fred's Car" to change?

**Comment by devernay** [comment]
but there's only one format in the project settings, right? "project format" is just shorthand for "the only format defined in the project settings, that is the project output format". Aren't you being a bit picky? Having a script name that doesn't correspond to the label is more bothering I think (the script name *won't* change for sure)

**Comment by Shrinks99** [comment]
I'm being _very_ picky and you're right, the script name being different is a complete bummer (unless you're willing to have breaking changes which honestly I personally think is reasonable as long as it's conveyed clearly in changelogs).  This script name discrepancy won't even be on the radar for what I suspect is most users, for advanced users it will just be another small inconsistency.

Relying on people having the same knowledge that you do about how what a given setting does and what data it will change sadly isn't a solution for intuitive software design.  Predictable and unified naming systems will seriously help people, especially new users.  When naming isn't unified how can we expect people to create mental models of what settings affect without brute force trial and error?  These types of small design issues really stick out to me, there's lots of inconsistency overall and it certainly don't help the user experience.
