### ISSUE TITLE
[Feature Request] Control interpolation between RotoPaint KeyFrames

### ISSUE THREAD

**Issue by pitbuster** [NatronGitHub/Natron#597]
Roto Nodes keyframes seem to be special compared with other nodes, since you can't adjust the interpolation (it is always linear). Adding this would be useful to do "drawn animation" like this https://www.youtube.com/watch?v=4sqm_13lyeo

Thanks in advance!

**Comment by devernay** [comment]
Natron is not a motion graphics application, so it misses many features like this one.

It seems like in Nuke it's always "Smooth (i.e. Catmull-Rom with no overshoot, see [here](https://learn.foundry.com/nuke/8.0/content/getting_started/using_interface/editing_curves.html) for Nuke's interpolation modes). However, I didn't see any mention in the manual of the interpolation method (see [the manual page on Animating Strokes](https://learn.foundry.com/nuke/8.0/content/user_guide/rotopaint/animating_strokes_shapes.html)).

- Do you think it should be "Smooth" by default, instead of "Linear"?
- Do you think it should be user-selectable (it doesn't seem to be selectable in Nuke)? If yes, what would the GUI look like to select the interpolation?

If what you want is that it's Smooth by default for new projects, then that change is rather easy. If you think there should be a GUI to customize it, then it will be more work.

**Comment by pitbuster** [comment]
Ideally, it should be user selectable (in the same way that interpolation for other keyframes work), but I understand that it is easier to implement Smooth by default and it may be enough (I don't have experience in Nuke to assess that, though).

**Comment by devernay** [comment]
Pull request https://github.com/NatronGitHub/Natron/pull/599 is under review and changes the default interpolation to "Smooth". This doesn't break existing projects, so hopefully it should be in the next version (2.4.0)

**Comment by Shrinks99** [comment]
Nuke's built in transform in the roto node has interpolation options like keyframes for any values in the program do in the curve editor but I don't know of any way to change the interpolation options for individual points.  If you create a roto shape in Nuke and go into the dope sheet and right click the keyframes you can set it to constant so it will jump from one keyframe right to another but none of the other ones seem to have any effect, maybe I just don't know what I'm doing but it feels kinda broken?  

Setting it to smooth in Natron should produce better results by default so that's a step in the right direction 👍 

If users are going to be given the ability to set it for the movement of actual points in each rotoshape maybe it should be another option in this panel?  I've never loved this UI and there's definitely some room for improvement as to what roto shape parameters should and shouldn't be in here but that's one option.  Could be cool to give every roto point a spot in the graph editor but that would also get ridiculous pretty fast.
<img width="588" alt="Screen Shot 2021-04-08 at 5 34 23 PM" src="https://user-images.githubusercontent.com/5672810/114099412-b982c600-9890-11eb-8a2b-8aa51ad51bbc.png">

Setting interpolation directly for each keyframe that users _don't_ want to be smooth in the graph editor for each roto shape would probably make the most sense, if you're going to change them all just select them all over there and set them to something else, no need to add another property to the roto layer stack.  As of right now I can't seem to change the spline animation keyframe interpolation (not using the built in transform) on a per-keyframe basis but that seems like a separate bug?  If you'd like I can do a real through test of the graph editor and dope sheets and find everything that should probably work differently after April is over.  Not sure if that is something you'd like to focus on for the next release after this one or whatever, maybe there are bigger priorities.
