### ISSUE TITLE
Clones poorly located upon creation

### ISSUE THREAD

**Issue by bonalex01dev** [NatronGitHub/Natron#627]
### Problem

When cloning a node with ALT+K the cloned node appear very far in the node graph

**Expected behavior:**
Cloned node is created close on the left of the source node

**Actual behavior:** [What actually happened]
Cloned node is created very far of the source node

![clone_poorly_located](https://user-images.githubusercontent.com/61953166/119105411-931e8180-ba1d-11eb-8103-edd1644b32d9.gif)

### Steps to Reproduce

1. select a node
2. press alt+k
3. look where the clone is

### Versions

* **Natron version/commit** All
* **OS version:** WIN10

**Comment by devernay** [comment]
Actually the expected behavior is to create the clones:
- at the center of the visible portion of the nodegraph if the action is selected from the menu, see https://github.com/NatronGitHub/Natron/blob/RB-2.4/Gui/NodeGraph35.cpp#L491
- at the cursor position when using alt+k (option+k on mac) see https://github.com/NatronGitHub/Natron/blob/RB-2.4/Gui/NodeGraph40.cpp#L340

My guess is that it is supposed to replicate the behavior of "paste".
Do you get a different behavior?

Maybe this should be documented?

**Comment by bonalex01dev** [comment]
Hi, I think I nailed it:
It seems related to the nodegraph loosing track of what area is actually displayed
To trigger the "clones appear very far" bug, I have to 
- create a node A and select it
- move the nodegraph view to move A out of the nodegraph view (put it below or to the left of the view)
- use the center selected node (F shortcut or right click>center on all nodes
- press Alt+k 
- that's it the clone of A is created very far.

Notes:
The F command doesn't center well the view if the node is outside the view ( ONLY 
![clone_bug_after_fit](https://user-images.githubusercontent.com/61953166/120710894-02d14980-c4bf-11eb-857c-6a851064e197.gif)
above or to the right) 
The problem arise even if you use another node B to make the "f shortcut trick"  and then clone node A. That's why I feel like Natron loose track of the actual view.
If zoom level is changed with the F command it seems to make the clone appear even farther. So zoom level seems "forgotten" too.

**Comment by bonalex01dev** [comment]
I see 
https://github.com/NatronGitHub/Natron/blob/RB-2.4/Gui/NodeGraph40.cpp#L340 uses QpointF
https://github.com/NatronGitHub/Natron/blob/RB-2.4/Gui/NodeGraph35.cpp#L491 uses QrectF
May it explain why Natron seems to loose track of the zoom level ?

**Comment by devernay** [comment]
fixed several NodeGraph issues in https://github.com/NatronGitHub/Natron/commit/dd334856de17d620f4c992a219eb6fa8451fad67:

- when using the right-click menu, use the click position to paste, rather than the visible area center (more control)
- pasting nodes from the menu was also affected
- fix behavior of "f" key (menu "Center on All Nodes") to always work (use moveRootInternal before centerOn to avoid negative values)
- this fixes *some* Navigator issues, but not all (see #491)

**Comment by bonalex01dev** [comment]
I tested 2.4.1 Alpha 2 on WIN10. It's great thanks for the motion path goodie
