### ISSUE TITLE
"Reset to default" on any parameter cannot be undone (was: Transform reset deletes all keys)

### ISSUE THREAD

**Issue by adamearle** [NatronGitHub/Natron#630]
### Problem
Transform reset doesn't work as expected. 
 
Can you imagine animating a character in 3D and the for your last mouth shape you decide Zero out (reset) attributes of the mouth do the last pose and it deletes all your work? It kinda doesn't make sense, does it?
 
 In my experience, there is a difference between resetting attributes and deleting all the keyframes of an attribute.

**Expected behavior:** 
reset should set attributes back to the there default not delete every keyframe you have already laid down previously.

**Actual behavior:** [What actually happened]
the resetting of the attributes will delete any keys that have been made before. this is a massive workflow issue
 
### Steps to Reproduce

1. Create a circle with a roto node.
2.  Attach a transform.
3. Prepare to make a bouncing ball.
4. Set the position of the roto and the transformation pivot point.
5. Key the default transformation frame 0.
6. Move the time slider to frame 12 and change the roto circles position up using the transform node (there should now be 2 keyframes).
7. Move to frame 24.
8. Reset the transform's position to set the last keyframe.

This is the most simplest of animations, but a very common working methodology. After resetting all your animation will be deleted. 

**IMPORTANT: Crtl +Z (undo) doesn't work on this operation**. Kind of a simple, but very dangerous and big problem. However, the menu item seems to state that this could be undone:
<img width="295" alt="image" src="https://user-images.githubusercontent.com/3778071/120550211-62d5cc00-c3a9-11eb-9221-326b0b856610.png">

The following methods should be implemented:
1. Reset (keeping already existing keyframe)
2. Remove all keyframes (this keeps the current setting and removes all keyframes)
3. Reset & remove all keyframes combining the first 2 methods.

I understand long menu names for performing an operation are not ideal. Having something that works and is clear would be more ideal than the current state.

### Versions 2.4
* **OS version:**  windows 10

Screen Shot of the node setup: and basic bouncing ball animation.
![Transform](https://user-images.githubusercontent.com/16330340/120270166-75d69680-c2ec-11eb-9026-82c815aab4ce.png)

In this example, you will see how keyframes being deleted. There is no retrieval of keyframes in any way.  Days of work can be lost in a single click

![GIF](https://user-images.githubusercontent.com/16330340/120270169-796a1d80-c2ec-11eb-8d41-0a3e051316a3.gif)

**Comment by Shrinks99** [comment]
+1 This all makes sense to me, especially because there are separate options that the user should select where they can expect to delete all keyframes (remove animation).

I would add one more step to the "expected results" though which is that the keyframe would be autokeyed after being reset to its initial position like everything else will when values are edited and that value is animated.  Implementing this means removing all keys and resetting values will now be a 2 step process but I think the benefits to that are pretty clear.  As mentioned, a "reset and remove animation" option could allow for some more efficiency there?

**Comment by devernay** [comment]
@adamearle first of all, I think the main bug is the fact that you cannot undo this operation, right? Can you file a separate bug on that (you can use the same images).

Second, it's not clear what you think "Reset (keeping already existing keyframe)" should do when you already have keyframes. Should it create a new keyframe with the default values? In this case I would call it "Set to default values" instead. So if there is no keyframe it would do the same as Reset, and if there are existing keyframes it would either add a keyframe or modify the current keyframe. Does it seem like an acceptable behavior? I don't think there is a lot of uses to this anyway: this is what you wanted to do because what you wanted to do what to set to the same values as another keyframe, so the real user experience improvement would be to be able to copy-paste keyframes, and this feature already exists, using the dope sheet: select a keyfram, copy it, set the time, select the parameter name in the dope sheet, and paste it.

Note that in Nuke, "Set to default" resets all the keyframes (but is undoable).

**Comment by devernay** [comment]
I also saw more feature in Nuke's transform that we may want to implement:
- the interact shows the trace of the center over the whole timeline, with keyframes clearly identified. That's definitely something we should have.
- when adjusting a value using the interact (in the viewer), it sets a keyframe on all knobs, not just the one that was adjusted. I don't see why it would be better. Maybe because it's better to have keyframes on all values by default? What do you think of it?

**Comment by Shrinks99** [comment]
As mentioned, in Nuke setting to default also removes all animation, I'd argue this behavior is a little inconsistent seeing as selecting "No Animation" brings up a dialogue box asking the user if they're sure they want to remove all animation, Nuke will then set the value to its current value on the current frame.  On the other hand, set to default just wipes everything immediately (though again as mentioned, it is undoable over in Nuke).

Splitting out "set to default" to two options: "Set to default and remove animation", and "Set to default" is one way this could go, alternatively it could simply set the values to default for that keyframe and there's no need for another option that removes and sets to default (my choice, users can always select "no animation" after which is more explicit).  If the goal is to simply keep parity with Nuke this feature works as expected.

> the interact shows the trace of the center over the whole timeline, with keyframes clearly identified. That's definitely something we should have.

If you're referring motion paths, this would be lovely though also a separate issue.  Happy to make that and detail how they are implemented in other comp programs if that would be helpful! :)

**Comment by devernay** [comment]
I think having the "undo" option would solve this issue.

I don't understand what is the use for "Set to default (but do not remove animation)": this sets a new keyframe to a value that is not useful 99.9% of the time, except in the case where you want to use it as a shortcut to return to the initial position, but it only works if the initial position is the default one. Looks like a non-feature to me.

As for the motion paths, I cannot go any farther than what Nuke does (no fancy editing of the whole path) because of how OpenFX works. It will only be a display feature, which would display the position of the rotation center (which combines translation and center parameters). Remember that Natron is not a motion graphics software.

**Comment by Shrinks99** [comment]
> except in the case where you want to use it as a shortcut to return to the initial position

Yep, that'd be it... I agree this is pretty limited so your solution works for me.  Perhaps the label could be altered to make its function clearer?

> It will only be a display feature, which would display the position of the rotation center

I'm A-OK with that, having the position information displayed is the most helpful part!

**Comment by devernay** [comment]
fixed: "Reset to default" can now be undone, and I also added drawing of the motion path to Transform and CornerPin

**Comment by bonalex01dev** [comment]
Wow, motion path, that's cool, thank you.

**Comment by devernay** [comment]
@bonalex01dev If someone ever wants to write something on motion path and how to edit it properly: I found it sometimes useful to directly manipulate the curves (and their tangents) for the translate parameter, to make the path rounder, etc. Now you get the feedback in the viewer.

**Comment by adamearle** [comment]
> I think having the "undo" option would solve this issue.
> 
> I don't understand what is the use for "Set to default (but do not remove animation)": this sets a new keyframe to a value that is not useful 99.9% of the time, except in the case where you want to use it as a shortcut to return to the initial position, but it only works if the initial position is the default one. Looks like a non-feature to me.
> 
> As for the motion paths, I cannot go any farther than what Nuke does (no fancy editing of the whole path) because of how OpenFX works. It will only be a display feature, which would display the position of the rotation center (which combines translation and center parameters). Remember that Natron is not a motion graphics software.


High mate sorry for the confusion.
Reset was meant to mean that the current keyframe. At the moment it removes every keyframe.
This resulted in the project taking way longer than it should have.

Also it might be time for the natron community to stop thinking that this will ever turn into Nuke. Nuke is absolutely terrible for animation that's why you always hear them bitch and complain when they have to keyframe.

You will find that my suggestions will make natron easier to use at a highlevel and a more pleasant experience. But if you want it to be like Nuke then I can't really help you here.
