### ISSUE TITLE
Can't enable Preview for a node from Python

### ISSUE THREAD

**Issue by bonalex01dev** [NatronGitHub/Natron#710]
Natron 2.4.1 win10

when I run:
myknob = currentNode.getParam('enablePreview')
myknob.setValue(True)
print 'testtrue'
currentNode.refreshUserParamsGUI()

Expected:
preview should appear in graph. Actually only checbox change in the properties

Notes:
- the same script for "disableNode" works ( big cross over node is drawn in graph)
- the preview appear as soon as I MANUALLY change any knob value in the properties

Some refresh code that is run in the UI should be executed from the python backend ?

**Comment by devernay** [comment]
Here: https://github.com/NatronGitHub/Natron/blob/205ba51abb6df8efbe0b24fd7e5f3a75b2205fe3/Engine/Node.cpp#L4899

It seems like we should have to add eValueChangedReasonNatronInternalEdited to trigger the update when set from Python. Can someone else confirm this is a good solution? @YakoYakoYokuYoku @rodlie? I can't think of a case where this would hurt

eValueChangedReasonSlaveRefresh was added in this commit:
https://github.com/NatronGitHub/Natron/commit/f2664a22c113fe197b51805f80bbcca098fe5332#r60978102

**Comment by YakoYakoYokuYoku** [comment]
Could apply the change locally, although I don't know how to replicate the issue yet neither running that Python snippet, whether the script code is invoked via cli, the Python tab or elsewhere.

**Comment by YakoYakoYokuYoku** [comment]
@devernay, managed to wrap around my mind, could replicate the issue and proved that your code was right.
Simply added a colorwheel and then run the sample Python snippet with some tweaks in a script editor tab. First try didn't work due to `previewKnobToggled` not being emitted as expected. Then applied the suggested change. And last try went successfully plus I could see a pixelated yet tiny color wheel on the node.
AFAICT I don't see any case that this would in fact hurt.
