### ISSUE TITLE
(Feature): Deprecate Python 2.7 in Natron

### ISSUE THREAD

**Issue by YakoYakoYokuYoku** [NatronGitHub/Natron#751]
### Make sure to follow our issue report guidelines

- [X] I have read the [feature request guidelines](https://hackmd.io/@natron-dev-awesome/B1SW6Hbau)
- [X] I have followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] This feature is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Abug+type%3Afeature+type%3Aidea) and is not a duplicate

### Provide a description of your feature request

The rationale of this is that the Python 2 series has officially reached its End Of Life. At the short run only brings some annoyances with parts of the codebase (and plugins by extent) having to be maintained for both the EOLed series and the current series. In the long run, however, it'll become much much more harder to maintain, for things like backporting security patches or dealing with an obsoleted ecosystem (NumPy, PySide, between others).

My intention is that the version 2.5 of Natron (or 2.6 otherwise) deprecates from the codebase and the documentation its support.

As a consequence of this is that we have to announce plus document the change and to confirm that the most popular and relevant plugins do indeed have support for Python 3.

### Is this a realistically implementable feature?

- [X] My feature is realistically implementable
- [ ] My feature is NOT realistically implementable

### Can you contribute in creating this feature?

- [ ] I am unable, or not willing to contribute to creating this feature
- [X] I am able and willing to contribute to the creation of this feature

### Additional details

If other maintainers want to join this, they are encouraged to do it.

**Comment by rodlie** [comment]
I suggest we use a "soft" deprecation in 2.5, and use that as an transition version ("fix your scripts before 2.6"). We have two builds, one for py2 and one for py3. Then in 2.6 we drop support for py2? (or at least stop producing builds)

**Comment by devernay** [comment]
I don't see the point in deprecating Python 2. This is a two-way door, let's keep it that way.

We can just stop making Python 2 binaries (as @rodlie suggests), but keep the code.

The code is there, and there are only minor differences with the Python3 code (I did the changes, so I know). People can write code that is [2-3 compatible (easy)](https://python-future.org/compatible_idioms.html) if they want to support both versions.

Who cares that Python 2 is EOL? This is just a scripting language in Natron. It works. If you care about security, there are probably 1000x more security issues in the Natron code (and the plugins) than in Python 2.

I don't see the point in deprecating Qt4 either, unless we really need to.

I hate breaking changes. Natron 3 had many breaking changes, and you see where this led: the engine is too buggy to use on real projects, and nice features (eg UI changes) are super hard to backport because of all the refactoring that happened.

If someone wants to "deprecate" stuff in Natron, then here's my advice: start another video compositing project from scratch. Just about everything has to be deprecated in the Natron codebase, and to be honest, Python 2 support is one of the things that works best.

Closing for now, we'll reopen it in two years if that becomes a real issue.
