### ISSUE TITLE
(Feature): Command Palette

### ISSUE THREAD

**Issue by erayerdin** [NatronGitHub/Natron#836]
### Make sure to follow our issue report guidelines

- [X] I have read the [feature request guidelines](https://hackmd.io/@natron-dev-awesome/B1SW6Hbau)
- [X] I have followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] This feature is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Abug+type%3Afeature+type%3Aidea) and is not a duplicate

### Provide a description of your feature request

Command palette is a feature that is widely adopted by code editors. [This](https://streamable.com/6gf2in) is how it is in VSCode. It is usually triggered by <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd>.

I think Natron would benefit so much from this, especially considering there are a lot of nodes, users could reach to what they want easily.

### Is this a realistically implementable feature?

- [X] My feature is realistically implementable
- [ ] My feature is NOT realistically implementable

### Can you contribute in creating this feature?

- [X] I am unable, or not willing to contribute to creating this feature
- [ ] I am able and willing to contribute to the creation of this feature

**Comment by rodlie** [comment]
Press the TAB key while the nodegraph has focus. Or do you want something else?

**Comment by erayerdin** [comment]
> Press the TAB key while the nodegraph has focus. Or do you want something else?

Wasn't aware this feature existed. I was trying to find every type of node navigating with my mouse.

Please, feel free to close.

**Comment by devernay** [comment]
Not closing. We need to make this shortcut more visible.
Maybe an item in the right-click menu (and btw I don't think than "Find" deserves that place and that room in the right click menu, especially since the shortcut is so easy to remember)
<img width="270" alt="image" src="https://user-images.githubusercontent.com/3778071/195390710-e1c24f35-250b-4f4c-962c-c9cdcce9735d.png">

**Comment by devernay** [comment]
I think all items below "Edit" should be in a submenu called "View".
And right below that View menu there should be an item "Insert node" hinting at the shortcut "TAB"

**Comment by Shrinks99** [comment]
Lots of these seem like menu bar items... Natron doesn't have a "View" menu but it probably should as you say.  It does have a "Display" menu which is where project settings are located?  I get the rationale behind this (Project settings are an actual window in Natron) but that should probably be moved to "File" to better match other UI conventions with "Display" becoming "View" and moving many of the right click menu options there?

Agreed about putting "Create Node" with the shortcut displayed in the right click menu.  Could also double it up in the menu bar which nobody will ever use but it will serve to direct people to the command field.

<img width="700" alt="Screen Shot 2022-10-14 at 2 48 52 PM" src="https://user-images.githubusercontent.com/5672810/195919401-48474c9e-028d-44bc-a325-2acf27dfc56e.png">

**Comment by devernay** [comment]
Most of these can't be in the menubar, because these shortcuts are specific to when the nodegraph has focus. A menubar that would change with focus would be very unusual, and probably not following most UI guidelines: this usually happens only when switching between applications

**Comment by Shrinks99** [comment]
+1, Menu bars shouldn't change with focus of in-application windows.  Some apps (Maya) change the menu bar out depending on what view a user is in, I hate this and it adds complexity.

I don't think "Show expressions links", "auto-hide optional inputs", "Display Cache Memory Consumption" and the like are focus-related despite the fact that they only pertain to a certain window?  Those seem more like global view options to me rather than context menu actions as they don't actually perform an action within the node graph, they only change how information is conveyed to users.  Items like "center on all nodes" and "Find" are good to keep in the context menu as these actions are accessed far more frequently and are dependent on the user currently operating the window.

Adding a separator in the menu bar "View" section to signify that these items are node-graph specific could be helpful.

**Comment by devernay** [comment]
Here's the new right-click nodegraph menu:
- the "tab" shortcut is more obvious
- all non-edit items were put in the "View" submenu
- I have no time to check if things can move to the global menubar, which may be complicated anyway

Does that look ok?
<img width="397" alt="image" src="https://user-images.githubusercontent.com/3778071/195936452-6a964e2f-44e9-4fd5-b6b7-dce0e4a97043.png">

**Comment by devernay** [comment]
fixed in https://github.com/NatronGitHub/Natron/commit/89bfde76ba4c489f9880d6ffd315a1966a49d6d0
