### ISSUE TITLE
(Feature): When wed have python3 in natron

### ISSUE THREAD

**Issue by a51kot** [NatronGitHub/Natron#842]
### Make sure to follow our issue report guidelines

- [X] I have read the [feature request guidelines](https://hackmd.io/@natron-dev-awesome/B1SW6Hbau)
- [X] I have followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] This feature is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Abug+type%3Afeature+type%3Aidea) and is not a duplicate

### Provide a description of your feature request

Python2 its oficially abandoned  and python staffers will not provide security updates

So im asking when Natron will move to python3  

Specially when many distros are thoeing python2 to the trashcan (unsafe + abandoned)  

### Is this a realistically implementable feature?

- [ ] My feature is realistically implementable
- [ ] My feature is NOT realistically implementable

### Can you contribute in creating this feature?

- [X] I am unable, or not willing to contribute to creating this feature
- [ ] I am able and willing to contribute to the creation of this feature

### Additional details

ANd question2 

Could i run the _old_ natron **2.4.3**  openfx (io/misc/aurora/gmic)  in natron **2.5**

or not

**Comment by devernay** [comment]
See https://github.com/NatronGitHub/Natron/issues/828 for Python 3 support: we are only waiting for Windows to be ready.

You don't have to care about python2 being "thrown to the trashcan", because:
- Natron binaries provide their own python interpreter, we don't depend on the system's python.
- Python code running inside Natron is usually minimal (and it's your code, mainly), so there's very little risk that your system gets compromised because of Python2. In fact there are probably 1000x more bugs, including security issues, in the Natron code than in Python
- Python2 is still maintained by the community, and security fixes are applied in the version bundled with Natron (on Linux, we take our patches from fedora).

The OpenFX plugins will be 100% backward-compatible.

**Comment by devernay** [comment]
In the mean time, if you want to test it, it's already available on macOS and Linux: https://github.com/NatronGitHub/Natron/releases/tag/v2.5.0-alpha.2
