### ISSUE TITLE
(Bug): Natron-2.5.0-macOS12-x86_64.dmg” cannot be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by nycanit** [NatronGitHub/Natron#888]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [ ] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

natron 2.5.0

### Operating system

macos ventura 13.4

### System specs

m1 processor 

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

Downloaded from your website but Macbook will not allow because your DMG are unsigned.

### What did you expect to happen? What happened instead?

I wanted to run Natron on my macbook.

### Step-by-step reproduction instructions

Download.
attempt to install.

**Comment by rodlie** [comment]
Hi,

We have experimental(?) builds for Apple Silicon: https://github.com/NatronGitHub/Natron/releases/download/v2.6.0-alpha1/Natron-RB-2.6-202305220414-dc73d01-macOS12-arm64.dmg

I only have Intel Mac's, so don't know the status of the build.

**Comment by devernay** [comment]
This is a FAQ on macOS, and not just for Natron.
A lot of non-paid software has the same issue because Apple asks for a paid subscription.

Answer from Apple:
https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

Answer from Natron's web site:
<img width="1014" alt="image" src="https://github.com/NatronGitHub/Natron/assets/3778071/5ef06f50-5793-46ea-8b29-201f951ef26a">

About the 2.6 builds mentionned by @rodlie: they run just fine, I use these, but they are not as thoroughly tested because they're using Qt5, that's all.
