### ISSUE TITLE
(Feature): Please Add Audio Support

### ISSUE THREAD

**Issue by AoriOjin** [NatronGitHub/Natron#923]
### Make sure to follow our issue report guidelines

- [X] I have read the [feature request guidelines](https://hackmd.io/@natron-dev-awesome/B1SW6Hbau)
- [X] I have followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] This feature is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Abug+type%3Afeature+type%3Aidea) and is not a duplicate

### Provide a description of your feature request

Hello everyone, I'm just passing by because I just found Natron, but... hey, no audio, no deal. That's just it, for me, audio playback shouldn't be a community plugin and exporting it should be the default.

I know you devs put a lot of effort into it and that I have no idea how to code or smth like that, but how do you do vfx  without audio? I need to listen to the lines being said, listen to the music, to the audio effects, everything needs to be in sync. Doesn't even need to show up in the timeline or whateves, but if I have a video or audio file, it should play something to my ears.

I may be back in a few years just to see the progress, but I'm truly sad to say I'll probably not use Natron again in a long time. Thanks for reading this soft rant, hope future users get some sound to work with :V

### Is this a realistically implementable feature?

- [X] My feature is realistically implementable
- [x] My feature is NOT realistically implementable

### Can you contribute in creating this feature?

- [X] I am unable, or not willing to contribute to creating this feature
- [ ] I am able and willing to contribute to the creation of this feature

**Comment by rodlie** [comment]
Compositing applications in general have lacking audio support (see Nuke/Fusion), as it's not a core feature for image compositing.

I would recommend using a better suited application (NLE or something similar).

**Comment by Arxareon** [comment]
Hi, I'd like to reopen this can of worms because synchronized playback of audio and video preview really is crucial for audiovisual work. It's not possible to compose an animated visual where certain music beats, sounds matter. I must see and hear both at the same time to feel if timings are truly right.

In many ways Natron could replace After Effects (which I want to eliminate from my workflow along with all other Adobe products which is really challenging but I'm determined) but not being able to have working audio in-editor is such a bummer.

I know about Audio_VLC, the community plugin. I installed it but unfortunately, no matter how I try it does not work. I completed the setup, added and manually verified the environmental variables for VLC too but it simply doesn't produce audio. I know the response might be to submit an issue for Audio_VLC's creator but I truly believe this should be a base feature _with perhaps the ability to change volume via keyframes and cut the length of the audio channel in the timeline to be able to compose the audio together with the visuals better - but these would be extra features for the future_. Playback of an audio file synced to the Viewer would already be very, very welcome.

Please, do reconsider!

**Comment by rodlie** [comment]
> In many ways Natron could replace After Effects

For compositing, sure. For animation/motion graphics? No.

> I know about Audio_VLC, the community plugin

It's a hack, don't expect it to work properly.

> Please, do reconsider!

Sorry, but none of the devs want to work on this feature. If someone want's to contribute to this feature feel free to send us a PR for review (or a plan for how this will be implemented).
