### ISSUE TITLE
(Bug): RoD seems to be not aligned to the exr datawindow with negative origin

### ISSUE THREAD

**Issue by bhack** [NatronGitHub/Natron#996]
### Make sure to follow our issue report guidelines

- [ ] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [ ] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

2.5.0

### Operating system

Ubuntu

### Did you install Natron using the official installer?

- [ ] Yes, I used the official installer
- [X] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [X] No, I installed Natron via another method

### What were you trying to do?

Reading an `exr` with negative origin `datawindow` and attach it to the viewer node. 

### What did you expect to happen? What happened instead?

Reading this `exr` and attaching the image read node to the viewer I've expected that the calcularted `RoD` respect `exr` `datawindow`.
Instead the `RoD` it is not aligned to the specified `datawindow`

### Step-by-step reproduction instructions

1. Start Natron
2. Use an Image->Read node to read the attached `exr` in the zip:
[checkerboard.zip](https://github.com/user-attachments/files/16600773/checkerboard.zip)

3. Attach it to the viewer

4. You will find that the `RoD` doesn't respect `exr` `datawindow`

**Comment by devernay** [comment]
The EXR has:
```
  displayWindow: [ 0, 0 - 3199 1799 ] 3200 x 1800
  dataWindow: [ -40, -11 - 3214 1822 ] 3255 x 1834
```
Now remember that exr boxes start at top left, and OpenFX at bottom left so we need to flip the bbox relative to the frame ([see code](https://github.com/NatronGitHub/openfx-io/blob/master/OIIO/ReadOIIO.cpp#L2748)).
So the OpenFX RoD should be:

left=-40,bottom=-23,right=3215,top=1811

why is right not 3214 as in the datawindow? Because 3214 is the last pixel coordinate in EXR, and the OpenFX bound is 3215. For example, an EXR datawindow of (0,0,0,0) is a 1-pixel image and has an OpenFX RoD of (0,0,1,1).

Natron says:

left = -41 bottom = -24 right = 3216 top = 1812

So it adds one pixel in every direction, and the reason is that edgePixels is Auto by default, which adds a black border in this case:
![image](https://github.com/user-attachments/assets/3055c945-a26e-4b40-829b-b861169a92bc)
 If you set edgePixels to Repeat, you get exactly the EXR dataWindow as the RoD.
![image](https://github.com/user-attachments/assets/a96c9c51-fa4f-4a90-bf9a-a805325af9b8)
